/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoPlayRouteImport } from './routes/video-play'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StashScenesRouteImport } from './routes/stash-scenes'
import { Route as MediaLibraryRouteImport } from './routes/media-library'
import { Route as EmbyPlayRouteImport } from './routes/emby-play'
import { Route as EmbyLibraryRouteImport } from './routes/emby-library'
import { Route as EmbyDetailRouteImport } from './routes/emby-detail'
import { Route as EmbyRouteImport } from './routes/emby'
import { Route as SettingRouteRouteImport } from './routes/setting/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingStashRouteImport } from './routes/setting/stash'
import { Route as SettingModelsRouteImport } from './routes/setting/models'
import { Route as SettingLibraryRouteImport } from './routes/setting/library'
import { Route as SettingFfmpegRouteImport } from './routes/setting/ffmpeg'
import { Route as SettingEmbyRouteImport } from './routes/setting/emby'
import { Route as SettingDefaultsRouteImport } from './routes/setting/defaults'

const VideoPlayRoute = VideoPlayRouteImport.update({
  id: '/video-play',
  path: '/video-play',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StashScenesRoute = StashScenesRouteImport.update({
  id: '/stash-scenes',
  path: '/stash-scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaLibraryRoute = MediaLibraryRouteImport.update({
  id: '/media-library',
  path: '/media-library',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbyPlayRoute = EmbyPlayRouteImport.update({
  id: '/emby-play',
  path: '/emby-play',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbyLibraryRoute = EmbyLibraryRouteImport.update({
  id: '/emby-library',
  path: '/emby-library',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbyDetailRoute = EmbyDetailRouteImport.update({
  id: '/emby-detail',
  path: '/emby-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbyRoute = EmbyRouteImport.update({
  id: '/emby',
  path: '/emby',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRouteRoute = SettingRouteRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingStashRoute = SettingStashRouteImport.update({
  id: '/stash',
  path: '/stash',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingModelsRoute = SettingModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingLibraryRoute = SettingLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingFfmpegRoute = SettingFfmpegRouteImport.update({
  id: '/ffmpeg',
  path: '/ffmpeg',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingEmbyRoute = SettingEmbyRouteImport.update({
  id: '/emby',
  path: '/emby',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingDefaultsRoute = SettingDefaultsRouteImport.update({
  id: '/defaults',
  path: '/defaults',
  getParentRoute: () => SettingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setting': typeof SettingRouteRouteWithChildren
  '/emby': typeof EmbyRoute
  '/emby-detail': typeof EmbyDetailRoute
  '/emby-library': typeof EmbyLibraryRoute
  '/emby-play': typeof EmbyPlayRoute
  '/media-library': typeof MediaLibraryRoute
  '/stash-scenes': typeof StashScenesRoute
  '/tasks': typeof TasksRoute
  '/video-play': typeof VideoPlayRoute
  '/setting/defaults': typeof SettingDefaultsRoute
  '/setting/emby': typeof SettingEmbyRoute
  '/setting/ffmpeg': typeof SettingFfmpegRoute
  '/setting/library': typeof SettingLibraryRoute
  '/setting/models': typeof SettingModelsRoute
  '/setting/stash': typeof SettingStashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setting': typeof SettingRouteRouteWithChildren
  '/emby': typeof EmbyRoute
  '/emby-detail': typeof EmbyDetailRoute
  '/emby-library': typeof EmbyLibraryRoute
  '/emby-play': typeof EmbyPlayRoute
  '/media-library': typeof MediaLibraryRoute
  '/stash-scenes': typeof StashScenesRoute
  '/tasks': typeof TasksRoute
  '/video-play': typeof VideoPlayRoute
  '/setting/defaults': typeof SettingDefaultsRoute
  '/setting/emby': typeof SettingEmbyRoute
  '/setting/ffmpeg': typeof SettingFfmpegRoute
  '/setting/library': typeof SettingLibraryRoute
  '/setting/models': typeof SettingModelsRoute
  '/setting/stash': typeof SettingStashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setting': typeof SettingRouteRouteWithChildren
  '/emby': typeof EmbyRoute
  '/emby-detail': typeof EmbyDetailRoute
  '/emby-library': typeof EmbyLibraryRoute
  '/emby-play': typeof EmbyPlayRoute
  '/media-library': typeof MediaLibraryRoute
  '/stash-scenes': typeof StashScenesRoute
  '/tasks': typeof TasksRoute
  '/video-play': typeof VideoPlayRoute
  '/setting/defaults': typeof SettingDefaultsRoute
  '/setting/emby': typeof SettingEmbyRoute
  '/setting/ffmpeg': typeof SettingFfmpegRoute
  '/setting/library': typeof SettingLibraryRoute
  '/setting/models': typeof SettingModelsRoute
  '/setting/stash': typeof SettingStashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setting'
    | '/emby'
    | '/emby-detail'
    | '/emby-library'
    | '/emby-play'
    | '/media-library'
    | '/stash-scenes'
    | '/tasks'
    | '/video-play'
    | '/setting/defaults'
    | '/setting/emby'
    | '/setting/ffmpeg'
    | '/setting/library'
    | '/setting/models'
    | '/setting/stash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setting'
    | '/emby'
    | '/emby-detail'
    | '/emby-library'
    | '/emby-play'
    | '/media-library'
    | '/stash-scenes'
    | '/tasks'
    | '/video-play'
    | '/setting/defaults'
    | '/setting/emby'
    | '/setting/ffmpeg'
    | '/setting/library'
    | '/setting/models'
    | '/setting/stash'
  id:
    | '__root__'
    | '/'
    | '/setting'
    | '/emby'
    | '/emby-detail'
    | '/emby-library'
    | '/emby-play'
    | '/media-library'
    | '/stash-scenes'
    | '/tasks'
    | '/video-play'
    | '/setting/defaults'
    | '/setting/emby'
    | '/setting/ffmpeg'
    | '/setting/library'
    | '/setting/models'
    | '/setting/stash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingRouteRoute: typeof SettingRouteRouteWithChildren
  EmbyRoute: typeof EmbyRoute
  EmbyDetailRoute: typeof EmbyDetailRoute
  EmbyLibraryRoute: typeof EmbyLibraryRoute
  EmbyPlayRoute: typeof EmbyPlayRoute
  MediaLibraryRoute: typeof MediaLibraryRoute
  StashScenesRoute: typeof StashScenesRoute
  TasksRoute: typeof TasksRoute
  VideoPlayRoute: typeof VideoPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-play': {
      id: '/video-play'
      path: '/video-play'
      fullPath: '/video-play'
      preLoaderRoute: typeof VideoPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stash-scenes': {
      id: '/stash-scenes'
      path: '/stash-scenes'
      fullPath: '/stash-scenes'
      preLoaderRoute: typeof StashScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-library': {
      id: '/media-library'
      path: '/media-library'
      fullPath: '/media-library'
      preLoaderRoute: typeof MediaLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emby-play': {
      id: '/emby-play'
      path: '/emby-play'
      fullPath: '/emby-play'
      preLoaderRoute: typeof EmbyPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emby-library': {
      id: '/emby-library'
      path: '/emby-library'
      fullPath: '/emby-library'
      preLoaderRoute: typeof EmbyLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emby-detail': {
      id: '/emby-detail'
      path: '/emby-detail'
      fullPath: '/emby-detail'
      preLoaderRoute: typeof EmbyDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emby': {
      id: '/emby'
      path: '/emby'
      fullPath: '/emby'
      preLoaderRoute: typeof EmbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting/stash': {
      id: '/setting/stash'
      path: '/stash'
      fullPath: '/setting/stash'
      preLoaderRoute: typeof SettingStashRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/models': {
      id: '/setting/models'
      path: '/models'
      fullPath: '/setting/models'
      preLoaderRoute: typeof SettingModelsRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/library': {
      id: '/setting/library'
      path: '/library'
      fullPath: '/setting/library'
      preLoaderRoute: typeof SettingLibraryRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/ffmpeg': {
      id: '/setting/ffmpeg'
      path: '/ffmpeg'
      fullPath: '/setting/ffmpeg'
      preLoaderRoute: typeof SettingFfmpegRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/emby': {
      id: '/setting/emby'
      path: '/emby'
      fullPath: '/setting/emby'
      preLoaderRoute: typeof SettingEmbyRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/defaults': {
      id: '/setting/defaults'
      path: '/defaults'
      fullPath: '/setting/defaults'
      preLoaderRoute: typeof SettingDefaultsRouteImport
      parentRoute: typeof SettingRouteRoute
    }
  }
}

interface SettingRouteRouteChildren {
  SettingDefaultsRoute: typeof SettingDefaultsRoute
  SettingEmbyRoute: typeof SettingEmbyRoute
  SettingFfmpegRoute: typeof SettingFfmpegRoute
  SettingLibraryRoute: typeof SettingLibraryRoute
  SettingModelsRoute: typeof SettingModelsRoute
  SettingStashRoute: typeof SettingStashRoute
}

const SettingRouteRouteChildren: SettingRouteRouteChildren = {
  SettingDefaultsRoute: SettingDefaultsRoute,
  SettingEmbyRoute: SettingEmbyRoute,
  SettingFfmpegRoute: SettingFfmpegRoute,
  SettingLibraryRoute: SettingLibraryRoute,
  SettingModelsRoute: SettingModelsRoute,
  SettingStashRoute: SettingStashRoute,
}

const SettingRouteRouteWithChildren = SettingRouteRoute._addFileChildren(
  SettingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingRouteRoute: SettingRouteRouteWithChildren,
  EmbyRoute: EmbyRoute,
  EmbyDetailRoute: EmbyDetailRoute,
  EmbyLibraryRoute: EmbyLibraryRoute,
  EmbyPlayRoute: EmbyPlayRoute,
  MediaLibraryRoute: MediaLibraryRoute,
  StashScenesRoute: StashScenesRoute,
  TasksRoute: TasksRoute,
  VideoPlayRoute: VideoPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
