/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoFolderScanRouteImport } from './routes/video-folder-scan'
import { Route as SubtitleWebRouteImport } from './routes/subtitle-web'
import { Route as SubtitleTranslateTaskRouteImport } from './routes/subtitle-translate-task'
import { Route as SubtitleTaskRouteImport } from './routes/subtitle-task'
import { Route as StashScenesRouteImport } from './routes/stash-scenes'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as JobDemoRouteImport } from './routes/job-demo'
import { Route as FileSystemRouteImport } from './routes/file-system'
import { Route as IndexRouteImport } from './routes/index'

const VideoFolderScanRoute = VideoFolderScanRouteImport.update({
  id: '/video-folder-scan',
  path: '/video-folder-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SubtitleWebRoute = SubtitleWebRouteImport.update({
  id: '/subtitle-web',
  path: '/subtitle-web',
  getParentRoute: () => rootRouteImport,
} as any)
const SubtitleTranslateTaskRoute = SubtitleTranslateTaskRouteImport.update({
  id: '/subtitle-translate-task',
  path: '/subtitle-translate-task',
  getParentRoute: () => rootRouteImport,
} as any)
const SubtitleTaskRoute = SubtitleTaskRouteImport.update({
  id: '/subtitle-task',
  path: '/subtitle-task',
  getParentRoute: () => rootRouteImport,
} as any)
const StashScenesRoute = StashScenesRouteImport.update({
  id: '/stash-scenes',
  path: '/stash-scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const JobDemoRoute = JobDemoRouteImport.update({
  id: '/job-demo',
  path: '/job-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FileSystemRoute = FileSystemRouteImport.update({
  id: '/file-system',
  path: '/file-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/file-system': typeof FileSystemRoute
  '/job-demo': typeof JobDemoRoute
  '/setting': typeof SettingRoute
  '/stash-scenes': typeof StashScenesRoute
  '/subtitle-task': typeof SubtitleTaskRoute
  '/subtitle-translate-task': typeof SubtitleTranslateTaskRoute
  '/subtitle-web': typeof SubtitleWebRoute
  '/video-folder-scan': typeof VideoFolderScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/file-system': typeof FileSystemRoute
  '/job-demo': typeof JobDemoRoute
  '/setting': typeof SettingRoute
  '/stash-scenes': typeof StashScenesRoute
  '/subtitle-task': typeof SubtitleTaskRoute
  '/subtitle-translate-task': typeof SubtitleTranslateTaskRoute
  '/subtitle-web': typeof SubtitleWebRoute
  '/video-folder-scan': typeof VideoFolderScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/file-system': typeof FileSystemRoute
  '/job-demo': typeof JobDemoRoute
  '/setting': typeof SettingRoute
  '/stash-scenes': typeof StashScenesRoute
  '/subtitle-task': typeof SubtitleTaskRoute
  '/subtitle-translate-task': typeof SubtitleTranslateTaskRoute
  '/subtitle-web': typeof SubtitleWebRoute
  '/video-folder-scan': typeof VideoFolderScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/file-system'
    | '/job-demo'
    | '/setting'
    | '/stash-scenes'
    | '/subtitle-task'
    | '/subtitle-translate-task'
    | '/subtitle-web'
    | '/video-folder-scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/file-system'
    | '/job-demo'
    | '/setting'
    | '/stash-scenes'
    | '/subtitle-task'
    | '/subtitle-translate-task'
    | '/subtitle-web'
    | '/video-folder-scan'
  id:
    | '__root__'
    | '/'
    | '/file-system'
    | '/job-demo'
    | '/setting'
    | '/stash-scenes'
    | '/subtitle-task'
    | '/subtitle-translate-task'
    | '/subtitle-web'
    | '/video-folder-scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FileSystemRoute: typeof FileSystemRoute
  JobDemoRoute: typeof JobDemoRoute
  SettingRoute: typeof SettingRoute
  StashScenesRoute: typeof StashScenesRoute
  SubtitleTaskRoute: typeof SubtitleTaskRoute
  SubtitleTranslateTaskRoute: typeof SubtitleTranslateTaskRoute
  SubtitleWebRoute: typeof SubtitleWebRoute
  VideoFolderScanRoute: typeof VideoFolderScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-folder-scan': {
      id: '/video-folder-scan'
      path: '/video-folder-scan'
      fullPath: '/video-folder-scan'
      preLoaderRoute: typeof VideoFolderScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subtitle-web': {
      id: '/subtitle-web'
      path: '/subtitle-web'
      fullPath: '/subtitle-web'
      preLoaderRoute: typeof SubtitleWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subtitle-translate-task': {
      id: '/subtitle-translate-task'
      path: '/subtitle-translate-task'
      fullPath: '/subtitle-translate-task'
      preLoaderRoute: typeof SubtitleTranslateTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subtitle-task': {
      id: '/subtitle-task'
      path: '/subtitle-task'
      fullPath: '/subtitle-task'
      preLoaderRoute: typeof SubtitleTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stash-scenes': {
      id: '/stash-scenes'
      path: '/stash-scenes'
      fullPath: '/stash-scenes'
      preLoaderRoute: typeof StashScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-demo': {
      id: '/job-demo'
      path: '/job-demo'
      fullPath: '/job-demo'
      preLoaderRoute: typeof JobDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-system': {
      id: '/file-system'
      path: '/file-system'
      fullPath: '/file-system'
      preLoaderRoute: typeof FileSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FileSystemRoute: FileSystemRoute,
  JobDemoRoute: JobDemoRoute,
  SettingRoute: SettingRoute,
  StashScenesRoute: StashScenesRoute,
  SubtitleTaskRoute: SubtitleTaskRoute,
  SubtitleTranslateTaskRoute: SubtitleTranslateTaskRoute,
  SubtitleWebRoute: SubtitleWebRoute,
  VideoFolderScanRoute: VideoFolderScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
