/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoPlayRouteImport } from './routes/video-play'
import { Route as VideoFolderScanRouteImport } from './routes/video-folder-scan'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StashScenesRouteImport } from './routes/stash-scenes'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as IndexRouteImport } from './routes/index'

const VideoPlayRoute = VideoPlayRouteImport.update({
  id: '/video-play',
  path: '/video-play',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoFolderScanRoute = VideoFolderScanRouteImport.update({
  id: '/video-folder-scan',
  path: '/video-folder-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StashScenesRoute = StashScenesRouteImport.update({
  id: '/stash-scenes',
  path: '/stash-scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setting': typeof SettingRoute
  '/stash-scenes': typeof StashScenesRoute
  '/tasks': typeof TasksRoute
  '/video-folder-scan': typeof VideoFolderScanRoute
  '/video-play': typeof VideoPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setting': typeof SettingRoute
  '/stash-scenes': typeof StashScenesRoute
  '/tasks': typeof TasksRoute
  '/video-folder-scan': typeof VideoFolderScanRoute
  '/video-play': typeof VideoPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setting': typeof SettingRoute
  '/stash-scenes': typeof StashScenesRoute
  '/tasks': typeof TasksRoute
  '/video-folder-scan': typeof VideoFolderScanRoute
  '/video-play': typeof VideoPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setting'
    | '/stash-scenes'
    | '/tasks'
    | '/video-folder-scan'
    | '/video-play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setting'
    | '/stash-scenes'
    | '/tasks'
    | '/video-folder-scan'
    | '/video-play'
  id:
    | '__root__'
    | '/'
    | '/setting'
    | '/stash-scenes'
    | '/tasks'
    | '/video-folder-scan'
    | '/video-play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingRoute: typeof SettingRoute
  StashScenesRoute: typeof StashScenesRoute
  TasksRoute: typeof TasksRoute
  VideoFolderScanRoute: typeof VideoFolderScanRoute
  VideoPlayRoute: typeof VideoPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-play': {
      id: '/video-play'
      path: '/video-play'
      fullPath: '/video-play'
      preLoaderRoute: typeof VideoPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-folder-scan': {
      id: '/video-folder-scan'
      path: '/video-folder-scan'
      fullPath: '/video-folder-scan'
      preLoaderRoute: typeof VideoFolderScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stash-scenes': {
      id: '/stash-scenes'
      path: '/stash-scenes'
      fullPath: '/stash-scenes'
      preLoaderRoute: typeof StashScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingRoute: SettingRoute,
  StashScenesRoute: StashScenesRoute,
  TasksRoute: TasksRoute,
  VideoFolderScanRoute: VideoFolderScanRoute,
  VideoPlayRoute: VideoPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
