//! OpenAPI 文档定义（仅 `openapi` feature 启用时编译）。

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(title = "media-admin API", version = "0.1.0"),
    paths(
        crate::routes::fs::list_handler,
        crate::routes::fs::read_text_handler,
        crate::routes::fs::delete_subtitle_handler,
        crate::routes::fs::video_probe_handler,
        crate::routes::fs::video_transcode_status_handler,
        crate::routes::fs::video_transcode_start_handler,
        crate::routes::jobs::generate_defaults_handler,
        crate::routes::jobs::generate_handler,
        crate::routes::jobs::generate_bulk_handler,
        crate::routes::jobs::scan_generate_handler,
        crate::routes::jobs::translate_handler,
        crate::routes::jobs::snapshot_handler,
        crate::routes::jobs::history_handler,
        crate::routes::jobs::exec_log_handler,
        crate::routes::jobs::active_tasks_handler,
        crate::routes::jobs::scheduler_pause_handler,
        crate::routes::jobs::scheduler_resume_handler,
        crate::routes::jobs::task_cancel_handler,
        crate::routes::jobs::task_pause_handler,
        crate::routes::jobs::task_resume_handler,
        crate::routes::jobs::delete_history_handler,
        crate::routes::jobs::rerun_history_handler,
        crate::routes::media_library::list_roots_handler,
        crate::routes::media_library::create_root_handler,
        crate::routes::media_library::delete_root_handler,
        crate::routes::media_library::scan_root_handler,
        crate::routes::media_library::list_files_handler,
        crate::routes::media_library::delete_videos_handler,
        crate::routes::settings::get_app_config,
        crate::routes::settings::put_app_config,
        crate::routes::setup::list_whisper_models_handler,
        crate::routes::setup::whisper_download_handler,
        crate::routes::setup::ffmpeg_status_handler,
        crate::routes::setup::ffmpeg_download_handler,
        crate::routes::stash::scenes_list_handler,
        crate::routes::subtitle_web::search_handler,
        crate::routes::subtitle_web::download_handler,
    ),
    components(schemas(
        ma_service::AppConfig,
        ma_service::SubtitleGenerateConfig,
        ma_service::SubtitleTranslateConfig,
        ma_service::VadConfig,
        ma_service::WhisperEngineConfig,
        ma_service::WhisperTranscribeConfig,
        ma_service::StashConnectConfig,
        ma_service::fs::FsDeleteReq,
        ma_service::fs::FsDeleteRes,
        ma_service::fs::FsListItem,
        ma_service::fs::FsListReq,
        ma_service::fs::FsReadTextReq,
        ma_service::fs::FsReadTextRes,
        ma_service::fs::VideoPlaybackProbeRes,
        ma_service::fs::VideoTranscodePhase,
        ma_service::fs::VideoTranscodeStatusRes,
        ma_service::job::ScanGenerateSubtitleReq,
        ma_service::job::ScanGenerateSubtitleRes,
        ma_service::job::SubtitleGenerateBulkFailedItem,
        ma_service::job::SubtitleGenerateBulkReq,
        ma_service::job::SubtitleGenerateBulkRes,
        ma_service::job::SubtitleGenerateDefaultsRes,
        ma_service::job::SubtitleGenerateReq,
        ma_service::job::SubtitleTranslateJobReq,
        ma_service::job::TaskmillCancelRes,
        ma_service::job::TaskmillControlOk,
        ma_service::job::TaskmillDeleteHistoryRes,
        ma_service::job::TaskmillSnapshot,
        ma_service::job::TimestampedSchedulerEvent,
        ma_service::media_library::MediaFileType,
        ma_service::media_library::MediaLibraryScanRes,
        ma_service::media_library::MediaRootCreateReq,
        ma_service::media_library::MediaRootRow,
        ma_service::media_library::MediaSubtitleRow,
        ma_service::media_library::MediaVideoDeleteReq,
        ma_service::media_library::MediaVideoDeleteRes,
        ma_service::media_library::MediaVideoRow,
        ma_service::media_library::MediaVideosPageRes,
        ma_service::media_library::MediaVideosQuery,
        ma_service::setup_download::DownloadJobStartRes,
        ma_service::setup_download::FfmpegDownloadStartReq,
        ma_service::setup_download::FfmpegSetupStatusRes,
        ma_service::setup_download::WhisperDownloadStartReq,
        ma_service::setup_download::WhisperModelItem,
        ma_service::setup_download::WhisperModelsListRes,
        ma_service::stash::StashCriterionModifier,
        ma_service::stash::StashDateCriterion,
        ma_service::stash::StashDuplicationCriterion,
        ma_service::stash::StashFilter,
        ma_service::stash::StashHierarchicalMultiCriterion,
        ma_service::stash::StashIdCriterion,
        ma_service::stash::StashIdsCriterion,
        ma_service::stash::StashIntCriterion,
        ma_service::stash::StashMultiCriterion,
        ma_service::stash::StashOrientation,
        ma_service::stash::StashOrientationCriterion,
        ma_service::stash::StashPathMapping,
        ma_service::stash::StashPhashDistanceCriterion,
        ma_service::stash::StashResolution,
        ma_service::stash::StashResolutionCriterion,
        ma_service::stash::StashSceneFile,
        ma_service::stash::StashSceneFilterType,
        ma_service::stash::StashSceneListReq,
        ma_service::stash::StashScenePaths,
        ma_service::stash::StashSceneRow,
        ma_service::stash::StashStringCriterion,
        ma_service::subtitles_web::DownloadBody,
        ma_service::subtitles_web::DownloadResponse,
        ma_service::subtitles_web::SubtitleWebRow,
        ma_service::subtitles_web::SubtitleWebSearchReq,
        ma_service::subtitles_web::SubtitleWebSearchRes,
        ma_utils::types::PageResult<ma_service::stash::StashSceneRow>,
    )),
    tags(
        (name = "fs", description = "本地文件与视频播放"),
        (name = "jobs", description = "字幕任务与队列控制"),
        (name = "media-library", description = "本地媒体库"),
        (name = "settings", description = "应用设置"),
        (name = "setup", description = "运行依赖安装"),
        (name = "stash", description = "Stash 集成"),
        (name = "subtitle-web", description = "在线字幕搜索与下载")
    )
)]
pub struct ApiDoc;
