/*
 Generated by typeshare 1.13.4
*/

export interface DownloadBody {
	video_path: string;
	subtitle_id: string;
}

export interface DownloadResponse {
	subtitle_path: string;
	record_id: number;
}

export interface FsListReq {
	parent_path?: string;
}

/** 搜索字幕结果 - 列表单项 */
export interface SubtitleWebRow {
	id: string;
	name: string;
	langs: string;
	ext: string;
	is_hash_match: boolean;
}

export interface SubtitleWebSearchReq {
	video_path: string;
}

/** 搜索字幕结果 */
export interface SubtitleWebSearchRes {
	/** 视频的绝对路径 */
	video_path: string;
	/** 视频的 cid */
	cid: string;
	/** 字幕列表 */
	items: SubtitleWebRow[];
}

