/*
 Generated by typeshare 1.13.4
*/

export interface DownloadBody {
	video_path: string;
	subtitle_id: string;
}

export interface DownloadResponse {
	subtitle_path: string;
	record_id: number;
}

export interface FsListReq {
	parent_path?: string;
}

/** VAD 配置 */
export interface VadConfig {
	/** 帧长 10/20/30（默认 30） */
	frame_ms: number;
	/** 模式 0..=3（越大越激进，默认 2） */
	mode: number;
	/** 语音段两侧 padding（ms）（默认 300） */
	padding_ms: number;
	/** 丢弃短于该值的语音段（ms）（默认 200） */
	min_speech_ms: number;
	/**
	 * 单段最大长度（ms），超过会被硬切。`0` 表示不限制。
	 * 默认 30000（30s）：whisper 内部以 30s 滑窗解码，限到 30s 速度与上下文都更稳。
	 */
	max_segment_ms: number;
}

/** whisper 引擎运行时配置（影响模型加载，启动期决定） */
export interface WhisperEngineConfig {
	/** 模型文件名 */
	model_filename: string;
	/** 是否使用 GPU */
	use_gpu: boolean;
	/**
	 * 是否启用 flash attention。
	 * 
	 * 注意：whisper.cpp 在 `BeamSearch + CUDA + flash_attn` 组合下会静默失败
	 * （forward pass 被跳过、瞬间返回 0 段）。本配置默认开启 flash_attn 是因为
	 * 默认解码策略是 Greedy，与 flash_attn 兼容。如果手动调到 BeamSearch
	 * 但发现段数总是 0，请把这里关掉。
	 */
	flash_attn: boolean;
}

/** whisper 解码可调参数（影响每次 transcribe 行为） */
export interface WhisperTranscribeOptions {
	/**
	 * 语言代码：
	 * - `None`：完全用 whisper.cpp 编译默认（通常是 "en"），不调用 `set_xxx`。
	 * 最稳，与本机验证可工作的旧版兼容。
	 * - `Some("auto")`：调用 `set_detect_language(true)` 自动检测。**警告**：
	 * 某些 CUDA build 下检测路径会让 forward pass 异常瞬退，遇到 0 段时回 `None`。
	 * - `Some("zh"/"en"/...)`：显式锁定语言代码。
	 */
	language?: string;
	/**
	 * 初始 prompt：可放专有名词、人名、风格示例（如 "以下是普通话简体中文字幕。"）。
	 * 为 `None` 时不调用 `set_initial_prompt`。
	 */
	initial_prompt?: string;
	/**
	 * beam search 束宽：> 1 走 BeamSearch；<= 1 走 Greedy。
	 * 
	 * 默认 1（Greedy）。BeamSearch 理论上更准，但部分 whisper.cpp CUDA 编译版本
	 * 会"静默失败"——forward pass 被跳过、瞬间返回 0 段。本机验证 OK 后再调高。
	 */
	beam_size: number;
	/**
	 * Greedy 模式下的候选数 best_of，仅当 `beam_size <= 1` 时生效。
	 * 
	 * 默认 1：与旧版 best_of 行为一致，确保 GPU 后端不会走异常 kernel 路径。
	 * 验证当前 build 兼容后可调到 5（whisper.cpp 默认值），轻微降低重复幻觉。
	 */
	greedy_best_of: number;
	/** CPU 解码线程数。0 表示 `whisper.cpp` 自动（min(4, hw_concurrency)）。 */
	n_threads: number;
	/** 是否在低音量片段做自动增益（peak<0.02 时拉到 0.8，封顶 20x） */
	auto_gain: boolean;
	/**
	 * 启用抗幻觉/重复参数组合
	 * （`temperature_inc` / `entropy_thold` / `logprob_thold` / `no_speech_thold` / ...）。
	 * 
	 * **默认 `false`**。这些参数虽然多数与 whisper.cpp 默认值相同，但**显式调用
	 * set_xxx** 在某些 CUDA build 上会让 forward pass 异常瞬退、整段返回 0。
	 * 本机确认能正常出字幕后再开启可获得更稳定的"不识别 → 跳过"行为。
	 */
	anti_hallucination: boolean;
}

/** 翻译选项 */
export interface SubtitleTranslateConfig {
	/** 模型名，默认 `tencent/Hunyuan-MT-7B` */
	model: string;
	/** 目标语言，例如 "Chinese"、"English"、"Japanese" */
	target_language: string;
	/** 并发数（同时在飞的请求数） */
	concurrency: number;
	/** 单批字幕条数。`>1` 时启用批量上下文翻译，`=1` 走逐条翻译。 */
	batch_size: number;
	/** 是否在翻译完成后删除原文 SRT。默认 `false`，两份文件并存便于核对。 */
	remove_source_srt: boolean;
}

export interface SubtitleGenerateConfig {
	video_path: string;
	vad_config?: VadConfig;
	whisper_engine_cfg?: WhisperEngineConfig;
	whisper_transcribe_options?: WhisperTranscribeOptions;
	translate_cfg?: SubtitleTranslateConfig;
}

export interface SubtitleTaskBulkCreateFailedItem {
	video_path: string;
	error: string;
}

export interface SubtitleTaskBulkCreateReq {
	configs: SubtitleGenerateConfig[];
	/** 若同 video_path 已存在 PENDING/RUNNING 任务则跳过（默认 true） */
	skip_if_exists: boolean;
}

export interface SubtitleTaskCreateRes {
	task_id: number;
	task_status: string;
	video_path: string;
	created_at: string;
	updated_at: string;
}

export interface SubtitleTaskBulkCreateRes {
	created: SubtitleTaskCreateRes[];
	skipped: string[];
	failed: SubtitleTaskBulkCreateFailedItem[];
}

export interface SubtitleTaskCreateReq {
	config: SubtitleGenerateConfig;
}

export interface SubtitleTaskDeleteReq {
	task_id: number;
}

export interface SubtitleTaskDeleteRes {
	ok: boolean;
}

export interface SubtitleTaskListReq {
	page: number;
	page_size: number;
	task_status?: string;
	video_path_contains?: string;
}

export interface SubtitleTaskRow {
	task_id: number;
	task_status: string;
	video_path: string;
	created_at: string;
	updated_at: string;
}

export interface SubtitleTaskListRes {
	items: SubtitleTaskRow[];
	total: number;
}

export interface SubtitleTaskQueuePauseReq {
}

export interface SubtitleTaskQueuePauseRes {
	ok: boolean;
}

export interface SubtitleTaskQueueResumeReq {
}

export interface SubtitleTaskQueueResumeRes {
	ok: boolean;
}

export interface SubtitleTaskQueueStatusReq {
}

export interface SubtitleTaskQueueStatusRes {
	/** RUNNING / PAUSING / PAUSED */
	status: string;
}

/** 搜索字幕结果 - 列表单项 */
export interface SubtitleWebRow {
	id: string;
	name: string;
	langs: string;
	ext: string;
	is_hash_match: boolean;
}

export interface SubtitleWebSearchReq {
	video_path: string;
}

/** 搜索字幕结果 */
export interface SubtitleWebSearchRes {
	/** 视频的绝对路径 */
	video_path: string;
	/** 视频的 cid */
	cid: string;
	/** 字幕列表 */
	items: SubtitleWebRow[];
}

export interface VideoFolderScanItem {
	video_name: string;
	video_path: string;
	video_size: number;
	/** 同目录、同 stem 的字幕文件名列表（不含路径） */
	subtitle_names: string[];
}

export interface VideoFolderScanReq {
	root_dir: string;
}

export interface VideoFolderScanRes {
	items: VideoFolderScanItem[];
}

