/*
 Generated by typeshare 1.13.4
*/

/** VAD 配置 */
export interface VadConfig {
	/** 帧长 10/20/30（默认 30） */
	frame_ms: number;
	/** 模式 0..=3（越大越激进，默认 2） */
	mode: number;
	/** 语音段两侧 padding（ms）（默认 300） */
	padding_ms: number;
	/** 丢弃短于该值的语音段（ms）（默认 200） */
	min_speech_ms: number;
	/**
	 * 单段最大长度（ms），超过会被硬切。`0` 表示不限制。
	 * 默认 30000（30s）：whisper 内部以 30s 滑窗解码，限到 30s 速度与上下文都更稳。
	 */
	max_segment_ms: number;
}

/** whisper 引擎运行时配置（影响模型加载，启动期决定） */
export interface WhisperEngineConfig {
	/** 模型文件名 */
	model_filename: string;
	/** 是否使用 GPU */
	use_gpu: boolean;
	/**
	 * 是否启用 flash attention。
	 * 
	 * 注意：whisper.cpp 在 `BeamSearch + CUDA + flash_attn` 组合下会静默失败
	 * （forward pass 被跳过、瞬间返回 0 段）。本配置默认开启 flash_attn 是因为
	 * 默认解码策略是 Greedy，与 flash_attn 兼容。如果手动调到 BeamSearch
	 * 但发现段数总是 0，请把这里关掉。
	 */
	flash_attn: boolean;
}

/** whisper 解码可调参数（影响每次 transcribe 行为） */
export interface WhisperTranscribeConfig {
	/**
	 * 语言代码：
	 * - `None`：完全用 whisper.cpp 编译默认（通常是 "en"），不调用 `set_xxx`。
	 * 最稳，与本机验证可工作的旧版兼容。
	 * - `Some("auto")`：调用 `set_detect_language(true)` 自动检测。**警告**：
	 * 某些 CUDA build 下检测路径会让 forward pass 异常瞬退，遇到 0 段时回 `None`。
	 * - `Some("zh"/"en"/...)`：显式锁定语言代码。
	 */
	language?: string;
	/**
	 * 初始 prompt：可放专有名词、人名、风格示例（如 "以下是普通话简体中文字幕。"）。
	 * 为 `None` 时不调用 `set_initial_prompt`。
	 */
	initial_prompt?: string;
	/**
	 * beam search 束宽：> 1 走 BeamSearch；<= 1 走 Greedy。
	 * 
	 * 默认 1（Greedy）。BeamSearch 理论上更准，但部分 whisper.cpp CUDA 编译版本
	 * 会"静默失败"——forward pass 被跳过、瞬间返回 0 段。本机验证 OK 后再调高。
	 */
	beam_size: number;
	/**
	 * Greedy 模式下的候选数 best_of，仅当 `beam_size <= 1` 时生效。
	 * 
	 * 默认 1：与旧版 best_of 行为一致，确保 GPU 后端不会走异常 kernel 路径。
	 * 验证当前 build 兼容后可调到 5（whisper.cpp 默认值），轻微降低重复幻觉。
	 */
	greedy_best_of: number;
	/** CPU 解码线程数。0 表示 `whisper.cpp` 自动（min(4, hw_concurrency)）。 */
	n_threads: number;
	/** 是否在低音量片段做自动增益（peak<0.02 时拉到 0.8，封顶 20x） */
	auto_gain: boolean;
	/**
	 * 启用抗幻觉/重复参数组合
	 * （`temperature_inc` / `entropy_thold` / `logprob_thold` / `no_speech_thold` / ...）。
	 * 
	 * **默认 `false`**。这些参数虽然多数与 whisper.cpp 默认值相同，但**显式调用
	 * set_xxx** 在某些 CUDA build 上会让 forward pass 异常瞬退、整段返回 0。
	 * 本机确认能正常出字幕后再开启可获得更稳定的"不识别 → 跳过"行为。
	 */
	anti_hallucination: boolean;
}

/** 翻译选项 */
export interface SubtitleTranslateConfig {
	/** 调用模型的基础 URL */
	base_url: string;
	/** 调用模型的 API 密钥 */
	api_key: string;
	/** 模型名，默认 `tencent/Hunyuan-MT-7B` */
	model: string;
	/** 目标语言，例如 "Chinese"、"English"、"Japanese" */
	target_language: string;
	/** 并发数（同时在飞的请求数） 默认 4 */
	concurrency: number;
	/** 单批字幕条数。`>1` 时启用批量上下文翻译，`=1` 走逐条翻译。 默认 8 */
	batch_size: number;
	/** 是否在翻译完成后删除原文 SRT。默认 `false`，两份文件并存便于核对。 */
	remove_source_srt: boolean;
}

/** 应用设置：识别流水线默认参数 + 翻译默认参数。 */
export interface AppConfig {
	vad_config: VadConfig;
	whisper_engine_config: WhisperEngineConfig;
	whisper_transcribe_config: WhisperTranscribeConfig;
	translate_config: SubtitleTranslateConfig;
}

export interface DownloadBody {
	video_path: string;
	subtitle_id: string;
}

export interface DownloadJobStartRes {
	job_id: string;
}

/** SSE / 内部共用的进度快照（JSON） */
export interface DownloadProgressSnapshot {
	phase: string;
	bytes_received: number;
	bytes_total?: number;
	message: string;
}

export interface DownloadResponse {
	subtitle_path: string;
	record_id: number;
}

export interface FfmpegDownloadStartReq {
}

/** FFmpeg 工具目录是否已安装可执行文件 */
export interface FfmpegSetupStatusRes {
	local_ready: boolean;
}

export interface FsDeleteReq {
	path: string;
}

export interface FsDeleteRes {
	ok: boolean;
}

export interface FsListReq {
	parent_path?: string;
}

export interface FsReadTextReq {
	path: string;
}

export interface FsReadTextRes {
	content: string;
}

export interface PageParams {
	current: number;
	page_size: number;
}

export interface PageResult<T> {
	data: T[];
	total: number;
}

/** Stash `CriterionModifier`（与 GraphQL 枚举值一致） */
export enum StashCriterionModifier {
	Eq = "=",
	Equals = "Equals",
	NotEq = "!=",
	NotEquals = "NotEquals",
	GreaterThanSymbol = ">",
	GreaterThan = "GreaterThan",
	LessThanSymbol = "<",
	LessThan = "LessThan",
	IsNull = "IS NULL",
	NotNull = "IS NOT NULL",
	IncludesAll = "INCLUDES ALL",
	Includes = "Includes",
	Excludes = "Excludes",
	MatchesRegex = "MATCHES REGEX",
	NotMatchesRegex = "NOT MATCHES REGEX",
	Between = ">= AND <=",
	NotBetween = "< OR >",
}

/** Stash `CustomFieldCriterionInput`（`value` 为 GraphQL `Any`，透传 JSON） */
export interface StashCustomFieldCriterion {
	field: string;
	value: Value[];
	modifier: StashCriterionModifier;
}

/** Stash `DateCriterionInput` / `TimestampCriterionInput` */
export interface StashDateCriterion {
	value: string;
	value2?: string;
	modifier: StashCriterionModifier;
}

/** Stash `DuplicationCriterionInput` */
export interface StashDuplicationCriterion {
	distance?: number;
	phash?: boolean;
	url?: boolean;
	stash_id?: boolean;
	title?: boolean;
}

/** Stash 场景列表查询（分页字段与 ProTable 对齐，服务端映射为 Stash `FindFilterType`） */
export interface StashFilter {
	page: number;
	page_size: number;
	q?: string;
	sort?: string;
	/** `ASC` 或 `DESC` */
	direction?: string;
}

/** Stash `HierarchicalMultiCriterionInput` */
export interface StashHierarchicalMultiCriterion {
	value?: string[];
	modifier: StashCriterionModifier;
	depth?: number;
	excludes?: string[];
}

/** Stash `StashIDCriterionInput` */
export interface StashIdCriterion {
	endpoint?: string;
	stash_id?: string;
	modifier: StashCriterionModifier;
}

/** Stash `StashIDsCriterionInput` */
export interface StashIdsCriterion {
	endpoint?: string;
	stash_ids?: string[];
	modifier: StashCriterionModifier;
}

/** Stash `IntCriterionInput` */
export interface StashIntCriterion {
	value: number;
	value2?: number;
	modifier: StashCriterionModifier;
}

/** Stash `MultiCriterionInput` */
export interface StashMultiCriterion {
	value?: string[];
	modifier: StashCriterionModifier;
	excludes?: string[];
}

/** Stash `OrientationEnum` */
export enum StashOrientation {
	Landscape = "LANDSCAPE",
	Portrait = "PORTRAIT",
	Square = "SQUARE",
}

/** Stash `OrientationCriterionInput` */
export interface StashOrientationCriterion {
	value: StashOrientation[];
}

/** Stash `PhashDistanceCriterionInput` */
export interface StashPhashDistanceCriterion {
	value: string;
	modifier: StashCriterionModifier;
	distance?: number;
}

/** Stash `ResolutionEnum` */
export enum StashResolution {
	VeryLow = "VERY_LOW",
	Low = "LOW",
	R360p = "R360P",
	Standard = "STANDARD",
	WebHd = "WEB_HD",
	StandardHd = "STANDARD_HD",
	FullHd = "FULL_HD",
	QuadHd = "QUAD_HD",
	FourK = "FOUR_K",
	FiveK = "FIVE_K",
	SixK = "SIX_K",
	SevenK = "SEVEN_K",
	EightK = "EIGHT_K",
	Huge = "HUGE",
}

/** Stash `ResolutionCriterionInput` */
export interface StashResolutionCriterion {
	value: StashResolution;
	modifier: StashCriterionModifier;
}

export interface StashSceneFile {
	path: string;
	basename: string;
}

/** Stash GraphQL `SceneFilterType`（字段与官方 schema 对齐，未建模的关联过滤器以 JSON 透传） */
export interface StashSceneFilterType {
	AND?: StashSceneFilterType;
	OR?: StashSceneFilterType;
	NOT?: StashSceneFilterType;
	id?: StashIntCriterion;
	title?: StashStringCriterion;
	code?: StashStringCriterion;
	details?: StashStringCriterion;
	director?: StashStringCriterion;
	oshash?: StashStringCriterion;
	checksum?: StashStringCriterion;
	phash?: StashStringCriterion;
	phash_distance?: StashPhashDistanceCriterion;
	path?: StashStringCriterion;
	file_count?: StashIntCriterion;
	rating100?: StashIntCriterion;
	organized?: boolean;
	o_counter?: StashIntCriterion;
	duplicated?: StashDuplicationCriterion;
	resolution?: StashResolutionCriterion;
	orientation?: StashOrientationCriterion;
	framerate?: StashIntCriterion;
	bitrate?: StashIntCriterion;
	video_codec?: StashStringCriterion;
	audio_codec?: StashStringCriterion;
	duration?: StashIntCriterion;
	has_markers?: string;
	is_missing?: string;
	studios?: StashHierarchicalMultiCriterion;
	movies?: StashMultiCriterion;
	groups?: StashHierarchicalMultiCriterion;
	galleries?: StashMultiCriterion;
	tags?: StashHierarchicalMultiCriterion;
	tag_count?: StashIntCriterion;
	performer_tags?: StashHierarchicalMultiCriterion;
	performer_favorite?: boolean;
	performer_age?: StashIntCriterion;
	performers?: StashMultiCriterion;
	performer_count?: StashIntCriterion;
	stash_id_endpoint?: StashIdCriterion;
	stash_ids_endpoint?: StashIdsCriterion;
	stash_id_count?: StashIntCriterion;
	url?: StashStringCriterion;
	interactive?: boolean;
	interactive_speed?: StashIntCriterion;
	captions?: StashStringCriterion;
	resume_time?: StashIntCriterion;
	play_count?: StashIntCriterion;
	play_duration?: StashIntCriterion;
	last_played_at?: StashDateCriterion;
	date?: StashDateCriterion;
	created_at?: StashDateCriterion;
	updated_at?: StashDateCriterion;
	/** 关联实体过滤器（结构体庞大，按需透传 Stash 原生 JSON） */
	galleries_filter?: Value;
	performers_filter?: Value;
	studios_filter?: Value;
	tags_filter?: Value;
	movies_filter?: Value;
	groups_filter?: Value;
	markers_filter?: Value;
	files_filter?: Value;
	custom_fields?: StashCustomFieldCriterion[];
}

export interface StashSceneListReq {
	filter: StashFilter;
	/** 对应 GraphQL `SceneFilterType` */
	scene_filter?: StashSceneFilterType;
	/** 对应 GraphQL `scene_ids` */
	scene_ids?: number[];
}

export interface StashScenePaths {
	screenshot: string;
	preview: string;
}

export interface StashSceneRow {
	id: string;
	title: string;
	date?: string;
	files: StashSceneFile[];
	paths: StashScenePaths;
}

/** Stash `StringCriterionInput` */
export interface StashStringCriterion {
	value: string;
	modifier: StashCriterionModifier;
}

export interface SubtitleGenerateBulkFailedItem {
	video_path: string;
	error: string;
}

export interface SubtitleGenerateConfig {
	vad_config?: VadConfig;
	whisper_engine_config?: WhisperEngineConfig;
	whisper_transcribe_config?: WhisperTranscribeConfig;
	translate_config?: SubtitleTranslateConfig;
}

export interface SubtitleGenerateBulkReq {
	video_paths: string[];
	/** `None` 表示整包采用全局默认。 */
	config?: SubtitleGenerateConfig;
	/** 若同 video_path 已有 pending/running 生成任务则跳过（默认 true） */
	skip_if_exists?: boolean;
}

export interface SubtitleGenerateBulkRes {
	submitted: string[];
	skipped: string[];
	failed: SubtitleGenerateBulkFailedItem[];
}

/** 新建任务表单的默认配置（来自当前全局 [`AppConfig`]）。 */
export interface SubtitleGenerateDefaultsRes {
	config: SubtitleGenerateConfig;
}

/** 提交单条字幕生成任务（`video_path` 与识别/翻译配置分离）。 */
export interface SubtitleGenerateReq {
	video_path: string;
	/** `None` 表示整包采用全局 [`AppConfig`] 对应的默认生成配置。 */
	config?: SubtitleGenerateConfig;
}

/** 字幕翻译任务（可独立提交，或由生成任务链式入队）。 */
export interface SubtitleTranslateJob {
	source_srt_path: string;
	config: SubtitleTranslateConfig;
}

/** 独立翻译任务提交体：`config == None` 表示使用全局翻译配置。 */
export interface SubtitleTranslateJobReq {
	source_srt_path: string;
	config?: SubtitleTranslateConfig;
}

/** 搜索字幕结果 - 列表单项 */
export interface SubtitleWebRow {
	id: string;
	name: string;
	langs: string;
	ext: string;
	is_hash_match: boolean;
}

export interface SubtitleWebSearchReq {
	video_path: string;
}

/** 搜索字幕结果 */
export interface SubtitleWebSearchRes {
	/** 视频的绝对路径 */
	video_path: string;
	/** 视频的 cid */
	cid: string;
	/** 字幕列表 */
	items: SubtitleWebRow[];
}

export interface VideoFolderScanItem {
	video_name: string;
	video_path: string;
	video_size: number;
	/** 同目录、同 stem 的字幕文件名列表（不含路径） */
	subtitle_names: string[];
}

export interface VideoFolderScanReq {
	root_dir: string;
}

export interface VideoFolderScanRes {
	items: VideoFolderScanItem[];
}

export interface WhisperDownloadStartReq {
	model_id: string;
}

/** Whisper 可下载项（静态目录） */
export interface WhisperModelItem {
	id: string;
	label: string;
	filename: string;
	description: string;
	/** 人类可读大小，如 "3.1 GiB" */
	size_hint: string;
	/** 模型目录下是否已有同名文件 */
	local_ready: boolean;
}

export interface WhisperModelsListRes {
	items: WhisperModelItem[];
}

