/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * media-admin API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

export const DeleteSubtitleFsBody = zod.object({
  "path": zod.string()
})

export const DeleteSubtitleFsResponse = zod.object({
  "ok": zod.boolean()
})


export const ListFsBody = zod.object({
  "parent_path": zod.string().nullish()
})

export const listFsResponseSizeMin = 0;



export const ListFsResponseItem = zod.object({
  "full_path": zod.string(),
  "is_dir": zod.boolean(),
  "last_modified": zod.iso.datetime({"offset":true}),
  "name": zod.string(),
  "size": zod.number().min(listFsResponseSizeMin)
})
export const ListFsResponse = zod.array(ListFsResponseItem)


export const ReadTextFsBody = zod.object({
  "path": zod.string()
})

export const ReadTextFsResponse = zod.object({
  "content": zod.string()
})


export const ProbeVideoFsQueryParams = zod.object({
  "path": zod.string()
})

export const ProbeVideoFsResponse = zod.object({
  "audio_codec": zod.string().nullish(),
  "container": zod.string().nullish(),
  "direct_playable": zod.boolean().describe('是否建议走直链（H.264\/AAC 等浏览器常见组合）'),
  "needs_transcode": zod.boolean().describe('是否建议服务端转码后再播'),
  "video_codec": zod.string().nullish()
})


export const StartVideoTranscodeFsQueryParams = zod.object({
  "path": zod.string()
})

export const StartVideoTranscodeFsResponse = zod.object({
  "message": zod.string().nullish(),
  "phase": zod.enum(['idle', 'running', 'ready', 'failed']),
  "progress": zod.number().nullish().describe('0.0–1.0，仅 `running` 时有效')
})


export const VideoTranscodeStatusFsQueryParams = zod.object({
  "path": zod.string()
})

export const VideoTranscodeStatusFsResponse = zod.object({
  "message": zod.string().nullish(),
  "phase": zod.enum(['idle', 'running', 'ready', 'failed']),
  "progress": zod.number().nullish().describe('0.0–1.0，仅 `running` 时有效')
})


export const ActiveTasksJobsQueryParams = zod.object({
  "limit": zod.number().optional()
})

export const ActiveTasksJobsResponseItem = zod.unknown()
export const ActiveTasksJobsResponse = zod.array(ActiveTasksJobsResponseItem)


export const execLogJobsQueryLimitMin = 0;



export const ExecLogJobsQueryParams = zod.object({
  "limit": zod.number().min(execLogJobsQueryLimitMin).optional()
})

export const ExecLogJobsResponseItem = zod.object({
  "event": zod.unknown(),
  "received_at": zod.iso.datetime({"offset":true})
}).describe('一条带接收时间的调度器事件，供任务页展示「执行中」流式日志。')
export const ExecLogJobsResponse = zod.array(ExecLogJobsResponseItem)


export const generateJobsBodyConfigTwoVadConfigTwoFrameMsMin = 0;

export const generateJobsBodyConfigTwoVadConfigTwoMaxSegmentMsMin = 0;

export const generateJobsBodyConfigTwoVadConfigTwoMinSpeechMsMin = 0;

export const generateJobsBodyConfigTwoVadConfigTwoModeMin = 0;

export const generateJobsBodyConfigTwoVadConfigTwoPaddingMsMin = 0;



export const GenerateJobsBody = zod.object({
  "config": zod.union([zod.null(),zod.object({
  "translate_config": zod.union([zod.null(),zod.object({
  "api_key": zod.string().describe('调用模型的 API 密钥'),
  "base_url": zod.string().describe('调用模型的基础 URL'),
  "batch_size": zod.number().describe('单批字幕条数。`>1` 时启用批量上下文翻译，`=1` 走逐条翻译。 默认 8'),
  "concurrency": zod.number().describe('并发数（同时在飞的请求数） 默认 4'),
  "model": zod.string().describe('模型名，默认 `tencent\/Hunyuan-MT-7B`'),
  "remove_source_srt": zod.boolean().describe('是否在翻译完成后删除原文 SRT。默认 `false`，两份文件并存便于核对。'),
  "target_language": zod.string().describe('目标语言，例如 \"Chinese\"、\"English\"、\"Japanese\"')
}).describe('翻译选项')]).optional(),
  "vad_config": zod.union([zod.null(),zod.object({
  "frame_ms": zod.number().min(generateJobsBodyConfigTwoVadConfigTwoFrameMsMin).describe('帧长 10\/20\/30（默认 30）'),
  "max_segment_ms": zod.number().min(generateJobsBodyConfigTwoVadConfigTwoMaxSegmentMsMin).describe('单段最大长度（ms），超过会被硬切。`0` 表示不限制。\n默认 30000（30s）：whisper 内部以 30s 滑窗解码，限到 30s 速度与上下文都更稳。'),
  "min_speech_ms": zod.number().min(generateJobsBodyConfigTwoVadConfigTwoMinSpeechMsMin).describe('丢弃短于该值的语音段（ms）（默认 200）'),
  "mode": zod.number().min(generateJobsBodyConfigTwoVadConfigTwoModeMin).describe('模式 0..=3（越大越激进，默认 2）'),
  "padding_ms": zod.number().min(generateJobsBodyConfigTwoVadConfigTwoPaddingMsMin).describe('语音段两侧 padding（ms）（默认 300）')
}).describe('VAD 配置')]).optional(),
  "whisper_engine_config": zod.union([zod.null(),zod.object({
  "flash_attn": zod.boolean().describe('是否启用 flash attention。\n\n注意：whisper.cpp 在 `BeamSearch + CUDA + flash_attn` 组合下会静默失败\n（forward pass 被跳过、瞬间返回 0 段）。本配置默认开启 flash_attn 是因为\n默认解码策略是 Greedy，与 flash_attn 兼容。如果手动调到 BeamSearch\n但发现段数总是 0，请把这里关掉。'),
  "model_filename": zod.string().describe('模型文件名'),
  "use_gpu": zod.boolean().describe('是否使用 GPU')
}).describe('whisper 引擎运行时配置（影响模型加载，启动期决定）')]).optional(),
  "whisper_transcribe_config": zod.union([zod.null(),zod.object({
  "anti_hallucination": zod.boolean().describe('启用抗幻觉\/重复参数组合\n（`temperature_inc` \/ `entropy_thold` \/ `logprob_thold` \/ `no_speech_thold` \/ ...）。\n\n\*\*默认 `false`\*\*。这些参数虽然多数与 whisper.cpp 默认值相同，但\*\*显式调用\nset_xxx\*\* 在某些 CUDA build 上会让 forward pass 异常瞬退、整段返回 0。\n本机确认能正常出字幕后再开启可获得更稳定的\"不识别 → 跳过\"行为。'),
  "auto_gain": zod.boolean().describe('是否在低音量片段做自动增益（peak<0.02 时拉到 0.8，封顶 20x）'),
  "beam_size": zod.number().describe('beam search 束宽：> 1 走 BeamSearch；<= 1 走 Greedy。\n\n默认 1（Greedy）。BeamSearch 理论上更准，但部分 whisper.cpp CUDA 编译版本\n会\"静默失败\"——forward pass 被跳过、瞬间返回 0 段。本机验证 OK 后再调高。'),
  "greedy_best_of": zod.number().describe('Greedy 模式下的候选数 best_of，仅当 `beam_size <= 1` 时生效。\n\n默认 1：与旧版 best_of 行为一致，确保 GPU 后端不会走异常 kernel 路径。\n验证当前 build 兼容后可调到 5（whisper.cpp 默认值），轻微降低重复幻觉。'),
  "initial_prompt": zod.string().nullish().describe('初始 prompt：可放专有名词、人名、风格示例（如 \"以下是普通话简体中文字幕。\"）。\n为 `None` 时不调用 `set_initial_prompt`。'),
  "language": zod.string().nullish().describe('语言代码：\n- `None`：完全用 whisper.cpp 编译默认（通常是 \"en\"），不调用 `set_xxx`。\n  最稳，与本机验证可工作的旧版兼容。\n- `Some(\"auto\")`：调用 `set_detect_language(true)` 自动检测。\*\*警告\*\*：\n  某些 CUDA build 下检测路径会让 forward pass 异常瞬退，遇到 0 段时回 `None`。\n- `Some(\"zh\"\/\"en\"\/...)`：显式锁定语言代码。'),
  "n_threads": zod.number().describe('CPU 解码线程数。0 表示 `whisper.cpp` 自动（min(4, hw_concurrency)）。')
}).describe('whisper 解码可调参数（影响每次 transcribe 行为）')]).optional()
}).describe('`None` 表示整包采用全局 [`AppConfig`] 对应的默认生成配置。')]).optional(),
  "video_path": zod.string()
}).describe('提交单条字幕生成任务（`video_path` 与识别\/翻译配置分离）。')


export const generateDefaultsJobsResponseConfigVadConfigTwoFrameMsMin = 0;

export const generateDefaultsJobsResponseConfigVadConfigTwoMaxSegmentMsMin = 0;

export const generateDefaultsJobsResponseConfigVadConfigTwoMinSpeechMsMin = 0;

export const generateDefaultsJobsResponseConfigVadConfigTwoModeMin = 0;

export const generateDefaultsJobsResponseConfigVadConfigTwoPaddingMsMin = 0;



export const GenerateDefaultsJobsResponse = zod.object({
  "config": zod.object({
  "translate_config": zod.union([zod.null(),zod.object({
  "api_key": zod.string().describe('调用模型的 API 密钥'),
  "base_url": zod.string().describe('调用模型的基础 URL'),
  "batch_size": zod.number().describe('单批字幕条数。`>1` 时启用批量上下文翻译，`=1` 走逐条翻译。 默认 8'),
  "concurrency": zod.number().describe('并发数（同时在飞的请求数） 默认 4'),
  "model": zod.string().describe('模型名，默认 `tencent\/Hunyuan-MT-7B`'),
  "remove_source_srt": zod.boolean().describe('是否在翻译完成后删除原文 SRT。默认 `false`，两份文件并存便于核对。'),
  "target_language": zod.string().describe('目标语言，例如 \"Chinese\"、\"English\"、\"Japanese\"')
}).describe('翻译选项')]).optional(),
  "vad_config": zod.union([zod.null(),zod.object({
  "frame_ms": zod.number().min(generateDefaultsJobsResponseConfigVadConfigTwoFrameMsMin).describe('帧长 10\/20\/30（默认 30）'),
  "max_segment_ms": zod.number().min(generateDefaultsJobsResponseConfigVadConfigTwoMaxSegmentMsMin).describe('单段最大长度（ms），超过会被硬切。`0` 表示不限制。\n默认 30000（30s）：whisper 内部以 30s 滑窗解码，限到 30s 速度与上下文都更稳。'),
  "min_speech_ms": zod.number().min(generateDefaultsJobsResponseConfigVadConfigTwoMinSpeechMsMin).describe('丢弃短于该值的语音段（ms）（默认 200）'),
  "mode": zod.number().min(generateDefaultsJobsResponseConfigVadConfigTwoModeMin).describe('模式 0..=3（越大越激进，默认 2）'),
  "padding_ms": zod.number().min(generateDefaultsJobsResponseConfigVadConfigTwoPaddingMsMin).describe('语音段两侧 padding（ms）（默认 300）')
}).describe('VAD 配置')]).optional(),
  "whisper_engine_config": zod.union([zod.null(),zod.object({
  "flash_attn": zod.boolean().describe('是否启用 flash attention。\n\n注意：whisper.cpp 在 `BeamSearch + CUDA + flash_attn` 组合下会静默失败\n（forward pass 被跳过、瞬间返回 0 段）。本配置默认开启 flash_attn 是因为\n默认解码策略是 Greedy，与 flash_attn 兼容。如果手动调到 BeamSearch\n但发现段数总是 0，请把这里关掉。'),
  "model_filename": zod.string().describe('模型文件名'),
  "use_gpu": zod.boolean().describe('是否使用 GPU')
}).describe('whisper 引擎运行时配置（影响模型加载，启动期决定）')]).optional(),
  "whisper_transcribe_config": zod.union([zod.null(),zod.object({
  "anti_hallucination": zod.boolean().describe('启用抗幻觉\/重复参数组合\n（`temperature_inc` \/ `entropy_thold` \/ `logprob_thold` \/ `no_speech_thold` \/ ...）。\n\n\*\*默认 `false`\*\*。这些参数虽然多数与 whisper.cpp 默认值相同，但\*\*显式调用\nset_xxx\*\* 在某些 CUDA build 上会让 forward pass 异常瞬退、整段返回 0。\n本机确认能正常出字幕后再开启可获得更稳定的\"不识别 → 跳过\"行为。'),
  "auto_gain": zod.boolean().describe('是否在低音量片段做自动增益（peak<0.02 时拉到 0.8，封顶 20x）'),
  "beam_size": zod.number().describe('beam search 束宽：> 1 走 BeamSearch；<= 1 走 Greedy。\n\n默认 1（Greedy）。BeamSearch 理论上更准，但部分 whisper.cpp CUDA 编译版本\n会\"静默失败\"——forward pass 被跳过、瞬间返回 0 段。本机验证 OK 后再调高。'),
  "greedy_best_of": zod.number().describe('Greedy 模式下的候选数 best_of，仅当 `beam_size <= 1` 时生效。\n\n默认 1：与旧版 best_of 行为一致，确保 GPU 后端不会走异常 kernel 路径。\n验证当前 build 兼容后可调到 5（whisper.cpp 默认值），轻微降低重复幻觉。'),
  "initial_prompt": zod.string().nullish().describe('初始 prompt：可放专有名词、人名、风格示例（如 \"以下是普通话简体中文字幕。\"）。\n为 `None` 时不调用 `set_initial_prompt`。'),
  "language": zod.string().nullish().describe('语言代码：\n- `None`：完全用 whisper.cpp 编译默认（通常是 \"en\"），不调用 `set_xxx`。\n  最稳，与本机验证可工作的旧版兼容。\n- `Some(\"auto\")`：调用 `set_detect_language(true)` 自动检测。\*\*警告\*\*：\n  某些 CUDA build 下检测路径会让 forward pass 异常瞬退，遇到 0 段时回 `None`。\n- `Some(\"zh\"\/\"en\"\/...)`：显式锁定语言代码。'),
  "n_threads": zod.number().describe('CPU 解码线程数。0 表示 `whisper.cpp` 自动（min(4, hw_concurrency)）。')
}).describe('whisper 解码可调参数（影响每次 transcribe 行为）')]).optional()
})
}).describe('新建任务表单的默认配置（来自当前全局 [`AppConfig`]）。')


export const generateBulkJobsBodyConfigTwoVadConfigTwoFrameMsMin = 0;

export const generateBulkJobsBodyConfigTwoVadConfigTwoMaxSegmentMsMin = 0;

export const generateBulkJobsBodyConfigTwoVadConfigTwoMinSpeechMsMin = 0;

export const generateBulkJobsBodyConfigTwoVadConfigTwoModeMin = 0;

export const generateBulkJobsBodyConfigTwoVadConfigTwoPaddingMsMin = 0;



export const GenerateBulkJobsBody = zod.object({
  "config": zod.union([zod.null(),zod.object({
  "translate_config": zod.union([zod.null(),zod.object({
  "api_key": zod.string().describe('调用模型的 API 密钥'),
  "base_url": zod.string().describe('调用模型的基础 URL'),
  "batch_size": zod.number().describe('单批字幕条数。`>1` 时启用批量上下文翻译，`=1` 走逐条翻译。 默认 8'),
  "concurrency": zod.number().describe('并发数（同时在飞的请求数） 默认 4'),
  "model": zod.string().describe('模型名，默认 `tencent\/Hunyuan-MT-7B`'),
  "remove_source_srt": zod.boolean().describe('是否在翻译完成后删除原文 SRT。默认 `false`，两份文件并存便于核对。'),
  "target_language": zod.string().describe('目标语言，例如 \"Chinese\"、\"English\"、\"Japanese\"')
}).describe('翻译选项')]).optional(),
  "vad_config": zod.union([zod.null(),zod.object({
  "frame_ms": zod.number().min(generateBulkJobsBodyConfigTwoVadConfigTwoFrameMsMin).describe('帧长 10\/20\/30（默认 30）'),
  "max_segment_ms": zod.number().min(generateBulkJobsBodyConfigTwoVadConfigTwoMaxSegmentMsMin).describe('单段最大长度（ms），超过会被硬切。`0` 表示不限制。\n默认 30000（30s）：whisper 内部以 30s 滑窗解码，限到 30s 速度与上下文都更稳。'),
  "min_speech_ms": zod.number().min(generateBulkJobsBodyConfigTwoVadConfigTwoMinSpeechMsMin).describe('丢弃短于该值的语音段（ms）（默认 200）'),
  "mode": zod.number().min(generateBulkJobsBodyConfigTwoVadConfigTwoModeMin).describe('模式 0..=3（越大越激进，默认 2）'),
  "padding_ms": zod.number().min(generateBulkJobsBodyConfigTwoVadConfigTwoPaddingMsMin).describe('语音段两侧 padding（ms）（默认 300）')
}).describe('VAD 配置')]).optional(),
  "whisper_engine_config": zod.union([zod.null(),zod.object({
  "flash_attn": zod.boolean().describe('是否启用 flash attention。\n\n注意：whisper.cpp 在 `BeamSearch + CUDA + flash_attn` 组合下会静默失败\n（forward pass 被跳过、瞬间返回 0 段）。本配置默认开启 flash_attn 是因为\n默认解码策略是 Greedy，与 flash_attn 兼容。如果手动调到 BeamSearch\n但发现段数总是 0，请把这里关掉。'),
  "model_filename": zod.string().describe('模型文件名'),
  "use_gpu": zod.boolean().describe('是否使用 GPU')
}).describe('whisper 引擎运行时配置（影响模型加载，启动期决定）')]).optional(),
  "whisper_transcribe_config": zod.union([zod.null(),zod.object({
  "anti_hallucination": zod.boolean().describe('启用抗幻觉\/重复参数组合\n（`temperature_inc` \/ `entropy_thold` \/ `logprob_thold` \/ `no_speech_thold` \/ ...）。\n\n\*\*默认 `false`\*\*。这些参数虽然多数与 whisper.cpp 默认值相同，但\*\*显式调用\nset_xxx\*\* 在某些 CUDA build 上会让 forward pass 异常瞬退、整段返回 0。\n本机确认能正常出字幕后再开启可获得更稳定的\"不识别 → 跳过\"行为。'),
  "auto_gain": zod.boolean().describe('是否在低音量片段做自动增益（peak<0.02 时拉到 0.8，封顶 20x）'),
  "beam_size": zod.number().describe('beam search 束宽：> 1 走 BeamSearch；<= 1 走 Greedy。\n\n默认 1（Greedy）。BeamSearch 理论上更准，但部分 whisper.cpp CUDA 编译版本\n会\"静默失败\"——forward pass 被跳过、瞬间返回 0 段。本机验证 OK 后再调高。'),
  "greedy_best_of": zod.number().describe('Greedy 模式下的候选数 best_of，仅当 `beam_size <= 1` 时生效。\n\n默认 1：与旧版 best_of 行为一致，确保 GPU 后端不会走异常 kernel 路径。\n验证当前 build 兼容后可调到 5（whisper.cpp 默认值），轻微降低重复幻觉。'),
  "initial_prompt": zod.string().nullish().describe('初始 prompt：可放专有名词、人名、风格示例（如 \"以下是普通话简体中文字幕。\"）。\n为 `None` 时不调用 `set_initial_prompt`。'),
  "language": zod.string().nullish().describe('语言代码：\n- `None`：完全用 whisper.cpp 编译默认（通常是 \"en\"），不调用 `set_xxx`。\n  最稳，与本机验证可工作的旧版兼容。\n- `Some(\"auto\")`：调用 `set_detect_language(true)` 自动检测。\*\*警告\*\*：\n  某些 CUDA build 下检测路径会让 forward pass 异常瞬退，遇到 0 段时回 `None`。\n- `Some(\"zh\"\/\"en\"\/...)`：显式锁定语言代码。'),
  "n_threads": zod.number().describe('CPU 解码线程数。0 表示 `whisper.cpp` 自动（min(4, hw_concurrency)）。')
}).describe('whisper 解码可调参数（影响每次 transcribe 行为）')]).optional()
}).describe('`None` 表示整包采用全局默认。')]).optional(),
  "skip_if_exists": zod.boolean().nullish().describe('若同 video_path 已有 pending\/running 生成任务则跳过（默认 true）'),
  "video_paths": zod.array(zod.string())
})

export const GenerateBulkJobsResponse = zod.object({
  "failed": zod.array(zod.object({
  "error": zod.string(),
  "video_path": zod.string()
})),
  "skipped": zod.array(zod.string()),
  "submitted": zod.array(zod.string())
})


export const HistoryJobsQueryParams = zod.object({
  "limit": zod.number().optional(),
  "offset": zod.number().optional()
})

export const HistoryJobsResponseItem = zod.unknown()
export const HistoryJobsResponse = zod.array(HistoryJobsResponseItem)


export const DeleteHistoryJobsParams = zod.object({
  "id": zod.number().describe('历史记录 ID')
})

export const DeleteHistoryJobsResponse = zod.object({
  "deleted": zod.boolean()
}).describe('删除历史记录结果。')


export const RerunHistoryJobsParams = zod.object({
  "id": zod.number().describe('历史记录 ID')
})

export const RerunHistoryJobsResponse = zod.object({
  "submitted": zod.boolean(),
  "task_id": zod.number().nullish()
}).describe('重新执行历史任务的结果。')


export const scanGenerateJobsBodyConfigTwoVadConfigTwoFrameMsMin = 0;

export const scanGenerateJobsBodyConfigTwoVadConfigTwoMaxSegmentMsMin = 0;

export const scanGenerateJobsBodyConfigTwoVadConfigTwoMinSpeechMsMin = 0;

export const scanGenerateJobsBodyConfigTwoVadConfigTwoModeMin = 0;

export const scanGenerateJobsBodyConfigTwoVadConfigTwoPaddingMsMin = 0;



export const ScanGenerateJobsBody = zod.object({
  "config": zod.union([zod.null(),zod.object({
  "translate_config": zod.union([zod.null(),zod.object({
  "api_key": zod.string().describe('调用模型的 API 密钥'),
  "base_url": zod.string().describe('调用模型的基础 URL'),
  "batch_size": zod.number().describe('单批字幕条数。`>1` 时启用批量上下文翻译，`=1` 走逐条翻译。 默认 8'),
  "concurrency": zod.number().describe('并发数（同时在飞的请求数） 默认 4'),
  "model": zod.string().describe('模型名，默认 `tencent\/Hunyuan-MT-7B`'),
  "remove_source_srt": zod.boolean().describe('是否在翻译完成后删除原文 SRT。默认 `false`，两份文件并存便于核对。'),
  "target_language": zod.string().describe('目标语言，例如 \"Chinese\"、\"English\"、\"Japanese\"')
}).describe('翻译选项')]).optional(),
  "vad_config": zod.union([zod.null(),zod.object({
  "frame_ms": zod.number().min(scanGenerateJobsBodyConfigTwoVadConfigTwoFrameMsMin).describe('帧长 10\/20\/30（默认 30）'),
  "max_segment_ms": zod.number().min(scanGenerateJobsBodyConfigTwoVadConfigTwoMaxSegmentMsMin).describe('单段最大长度（ms），超过会被硬切。`0` 表示不限制。\n默认 30000（30s）：whisper 内部以 30s 滑窗解码，限到 30s 速度与上下文都更稳。'),
  "min_speech_ms": zod.number().min(scanGenerateJobsBodyConfigTwoVadConfigTwoMinSpeechMsMin).describe('丢弃短于该值的语音段（ms）（默认 200）'),
  "mode": zod.number().min(scanGenerateJobsBodyConfigTwoVadConfigTwoModeMin).describe('模式 0..=3（越大越激进，默认 2）'),
  "padding_ms": zod.number().min(scanGenerateJobsBodyConfigTwoVadConfigTwoPaddingMsMin).describe('语音段两侧 padding（ms）（默认 300）')
}).describe('VAD 配置')]).optional(),
  "whisper_engine_config": zod.union([zod.null(),zod.object({
  "flash_attn": zod.boolean().describe('是否启用 flash attention。\n\n注意：whisper.cpp 在 `BeamSearch + CUDA + flash_attn` 组合下会静默失败\n（forward pass 被跳过、瞬间返回 0 段）。本配置默认开启 flash_attn 是因为\n默认解码策略是 Greedy，与 flash_attn 兼容。如果手动调到 BeamSearch\n但发现段数总是 0，请把这里关掉。'),
  "model_filename": zod.string().describe('模型文件名'),
  "use_gpu": zod.boolean().describe('是否使用 GPU')
}).describe('whisper 引擎运行时配置（影响模型加载，启动期决定）')]).optional(),
  "whisper_transcribe_config": zod.union([zod.null(),zod.object({
  "anti_hallucination": zod.boolean().describe('启用抗幻觉\/重复参数组合\n（`temperature_inc` \/ `entropy_thold` \/ `logprob_thold` \/ `no_speech_thold` \/ ...）。\n\n\*\*默认 `false`\*\*。这些参数虽然多数与 whisper.cpp 默认值相同，但\*\*显式调用\nset_xxx\*\* 在某些 CUDA build 上会让 forward pass 异常瞬退、整段返回 0。\n本机确认能正常出字幕后再开启可获得更稳定的\"不识别 → 跳过\"行为。'),
  "auto_gain": zod.boolean().describe('是否在低音量片段做自动增益（peak<0.02 时拉到 0.8，封顶 20x）'),
  "beam_size": zod.number().describe('beam search 束宽：> 1 走 BeamSearch；<= 1 走 Greedy。\n\n默认 1（Greedy）。BeamSearch 理论上更准，但部分 whisper.cpp CUDA 编译版本\n会\"静默失败\"——forward pass 被跳过、瞬间返回 0 段。本机验证 OK 后再调高。'),
  "greedy_best_of": zod.number().describe('Greedy 模式下的候选数 best_of，仅当 `beam_size <= 1` 时生效。\n\n默认 1：与旧版 best_of 行为一致，确保 GPU 后端不会走异常 kernel 路径。\n验证当前 build 兼容后可调到 5（whisper.cpp 默认值），轻微降低重复幻觉。'),
  "initial_prompt": zod.string().nullish().describe('初始 prompt：可放专有名词、人名、风格示例（如 \"以下是普通话简体中文字幕。\"）。\n为 `None` 时不调用 `set_initial_prompt`。'),
  "language": zod.string().nullish().describe('语言代码：\n- `None`：完全用 whisper.cpp 编译默认（通常是 \"en\"），不调用 `set_xxx`。\n  最稳，与本机验证可工作的旧版兼容。\n- `Some(\"auto\")`：调用 `set_detect_language(true)` 自动检测。\*\*警告\*\*：\n  某些 CUDA build 下检测路径会让 forward pass 异常瞬退，遇到 0 段时回 `None`。\n- `Some(\"zh\"\/\"en\"\/...)`：显式锁定语言代码。'),
  "n_threads": zod.number().describe('CPU 解码线程数。0 表示 `whisper.cpp` 自动（min(4, hw_concurrency)）。')
}).describe('whisper 解码可调参数（影响每次 transcribe 行为）')]).optional()
}).describe('`None` 表示整包采用全局默认。')]).optional(),
  "folder_path": zod.string(),
  "skip_if_exists": zod.boolean().nullish().describe('若同 video_path 已有 pending\/running 生成任务则跳过（默认 true）')
})

export const scanGenerateJobsResponseMatchedVideosMin = 0;

export const scanGenerateJobsResponseScanRemovedMin = 0;

export const scanGenerateJobsResponseScanScannedMin = 0;

export const scanGenerateJobsResponseScanSubtitlesMin = 0;

export const scanGenerateJobsResponseScanVideosMin = 0;

export const scanGenerateJobsResponseWithoutSubtitlesMin = 0;



export const ScanGenerateJobsResponse = zod.object({
  "failed": zod.array(zod.object({
  "error": zod.string(),
  "video_path": zod.string()
})),
  "matched_videos": zod.number().min(scanGenerateJobsResponseMatchedVideosMin),
  "scan": zod.object({
  "removed": zod.number().min(scanGenerateJobsResponseScanRemovedMin),
  "scanned": zod.number().min(scanGenerateJobsResponseScanScannedMin),
  "subtitles": zod.number().min(scanGenerateJobsResponseScanSubtitlesMin),
  "videos": zod.number().min(scanGenerateJobsResponseScanVideosMin)
}).describe('媒体库扫描结果摘要。'),
  "skipped": zod.array(zod.string()),
  "submitted": zod.array(zod.string()),
  "without_subtitles": zod.number().min(scanGenerateJobsResponseWithoutSubtitlesMin)
})


export const PauseSchedulerJobsResponse = zod.object({
  "ok": zod.boolean()
}).describe('通用成功响应。')


export const ResumeSchedulerJobsResponse = zod.object({
  "ok": zod.boolean()
}).describe('通用成功响应。')


export const SnapshotJobsResponse = zod.object({
  "metrics": zod.unknown(),
  "scheduler": zod.unknown()
})


export const CancelTaskJobsParams = zod.object({
  "id": zod.number().describe('任务 ID')
})

export const CancelTaskJobsResponse = zod.object({
  "cancelled": zod.boolean()
}).describe('取消任务结果。')


export const PauseTaskJobsParams = zod.object({
  "id": zod.number().describe('任务 ID')
})

export const PauseTaskJobsResponse = zod.object({
  "ok": zod.boolean()
}).describe('通用成功响应。')


export const ResumeTaskJobsParams = zod.object({
  "id": zod.number().describe('任务 ID')
})

export const ResumeTaskJobsResponse = zod.object({
  "ok": zod.boolean()
}).describe('通用成功响应。')


export const TranslateJobsBody = zod.object({
  "config": zod.union([zod.null(),zod.object({
  "api_key": zod.string().describe('调用模型的 API 密钥'),
  "base_url": zod.string().describe('调用模型的基础 URL'),
  "batch_size": zod.number().describe('单批字幕条数。`>1` 时启用批量上下文翻译，`=1` 走逐条翻译。 默认 8'),
  "concurrency": zod.number().describe('并发数（同时在飞的请求数） 默认 4'),
  "model": zod.string().describe('模型名，默认 `tencent\/Hunyuan-MT-7B`'),
  "remove_source_srt": zod.boolean().describe('是否在翻译完成后删除原文 SRT。默认 `false`，两份文件并存便于核对。'),
  "target_language": zod.string().describe('目标语言，例如 \"Chinese\"、\"English\"、\"Japanese\"')
}).describe('翻译选项')]).optional(),
  "source_srt_path": zod.string()
}).describe('独立翻译任务提交体：`config == None` 表示使用全局翻译配置。')


export const ListFilesMediaLibraryQueryParams = zod.object({
  "root_id": zod.number().nullish(),
  "q": zod.string().nullish(),
  "has_subtitle": zod.boolean().nullish(),
  "current": zod.number().nullish(),
  "page_size": zod.number().nullish()
})

export const listFilesMediaLibraryResponseDataItemFileSizeMin = 0;

export const listFilesMediaLibraryResponseDataItemSubtitleCountMin = 0;

export const listFilesMediaLibraryResponseDataItemSubtitlesItemFileSizeMin = 0;



export const ListFilesMediaLibraryResponse = zod.object({
  "data": zod.array(zod.object({
  "file_name": zod.string(),
  "file_path": zod.string(),
  "file_size": zod.number().min(listFilesMediaLibraryResponseDataItemFileSizeMin),
  "id": zod.number(),
  "modified_at": zod.string(),
  "root_id": zod.number(),
  "scanned_at": zod.string(),
  "subtitle_count": zod.number().min(listFilesMediaLibraryResponseDataItemSubtitleCountMin),
  "subtitles": zod.array(zod.object({
  "file_name": zod.string(),
  "file_path": zod.string(),
  "file_size": zod.number().min(listFilesMediaLibraryResponseDataItemSubtitlesItemFileSizeMin),
  "id": zod.number(),
  "modified_at": zod.string(),
  "scanned_at": zod.string()
}).describe('视频拥有的字幕文件列表行。'))
}).describe('媒体库视频列表行。')),
  "total": zod.number()
}).describe('媒体库视频分页查询结果。')


export const ListRootsMediaLibraryResponseItem = zod.object({
  "created_at": zod.string(),
  "id": zod.number(),
  "last_scanned_at": zod.string().nullish(),
  "name": zod.string(),
  "path": zod.string(),
  "updated_at": zod.string()
}).describe('媒体资源根目录列表行。')
export const ListRootsMediaLibraryResponse = zod.array(ListRootsMediaLibraryResponseItem)


export const CreateRootMediaLibraryBody = zod.object({
  "name": zod.string().nullish(),
  "path": zod.string()
}).describe('新增媒体资源根目录请求。')

export const CreateRootMediaLibraryResponse = zod.object({
  "created_at": zod.string(),
  "id": zod.number(),
  "last_scanned_at": zod.string().nullish(),
  "name": zod.string(),
  "path": zod.string(),
  "updated_at": zod.string()
}).describe('媒体资源根目录列表行。')


export const DeleteRootMediaLibraryParams = zod.object({
  "id": zod.number().describe('媒体资源目录 ID')
})


export const ScanRootMediaLibraryParams = zod.object({
  "id": zod.number().describe('媒体资源目录 ID')
})


export const DeleteVideosMediaLibraryBody = zod.object({
  "video_paths": zod.array(zod.string())
}).describe('删除媒体库视频请求。')

export const deleteVideosMediaLibraryResponseDeletedSubtitlesMin = 0;

export const deleteVideosMediaLibraryResponseDeletedVideosMin = 0;



export const DeleteVideosMediaLibraryResponse = zod.object({
  "deleted_subtitles": zod.number().min(deleteVideosMediaLibraryResponseDeletedSubtitlesMin),
  "deleted_videos": zod.number().min(deleteVideosMediaLibraryResponseDeletedVideosMin)
}).describe('删除媒体库视频结果摘要。')


/**
 * @summary 返回当前全局配置。
 */
export const getAppConfigSettingsResponseVadConfigFrameMsMin = 0;

export const getAppConfigSettingsResponseVadConfigMaxSegmentMsMin = 0;

export const getAppConfigSettingsResponseVadConfigMinSpeechMsMin = 0;

export const getAppConfigSettingsResponseVadConfigModeMin = 0;

export const getAppConfigSettingsResponseVadConfigPaddingMsMin = 0;



export const GetAppConfigSettingsResponse = zod.object({
  "stash_config": zod.object({
  "api_key": zod.string().describe('GraphQL \/ 媒体请求使用的 ApiKey；无鉴权时可留空'),
  "base_url": zod.string().describe('实例根地址，如 `http:\/\/127.0.0.1:9999`'),
  "path_mappings": zod.array(zod.object({
  "local_prefix": zod.string().describe('本服务运行环境可访问的本地路径前缀。'),
  "stash_prefix": zod.string().describe('Stash 返回的文件路径前缀。')
}).describe('Stash 文件路径到本服务本地路径的前缀映射。')).optional().describe('Stash 视角文件路径到本服务本地文件路径的前缀映射。')
}).optional().describe('旧版 `app_config.json` 无此字段时反序列化为 [`StashConnectConfig::default`]。'),
  "translate_config": zod.object({
  "api_key": zod.string().describe('调用模型的 API 密钥'),
  "base_url": zod.string().describe('调用模型的基础 URL'),
  "batch_size": zod.number().describe('单批字幕条数。`>1` 时启用批量上下文翻译，`=1` 走逐条翻译。 默认 8'),
  "concurrency": zod.number().describe('并发数（同时在飞的请求数） 默认 4'),
  "model": zod.string().describe('模型名，默认 `tencent\/Hunyuan-MT-7B`'),
  "remove_source_srt": zod.boolean().describe('是否在翻译完成后删除原文 SRT。默认 `false`，两份文件并存便于核对。'),
  "target_language": zod.string().describe('目标语言，例如 \"Chinese\"、\"English\"、\"Japanese\"')
}).describe('翻译选项'),
  "vad_config": zod.object({
  "frame_ms": zod.number().min(getAppConfigSettingsResponseVadConfigFrameMsMin).describe('帧长 10\/20\/30（默认 30）'),
  "max_segment_ms": zod.number().min(getAppConfigSettingsResponseVadConfigMaxSegmentMsMin).describe('单段最大长度（ms），超过会被硬切。`0` 表示不限制。\n默认 30000（30s）：whisper 内部以 30s 滑窗解码，限到 30s 速度与上下文都更稳。'),
  "min_speech_ms": zod.number().min(getAppConfigSettingsResponseVadConfigMinSpeechMsMin).describe('丢弃短于该值的语音段（ms）（默认 200）'),
  "mode": zod.number().min(getAppConfigSettingsResponseVadConfigModeMin).describe('模式 0..=3（越大越激进，默认 2）'),
  "padding_ms": zod.number().min(getAppConfigSettingsResponseVadConfigPaddingMsMin).describe('语音段两侧 padding（ms）（默认 300）')
}).describe('VAD 配置'),
  "whisper_engine_config": zod.object({
  "flash_attn": zod.boolean().describe('是否启用 flash attention。\n\n注意：whisper.cpp 在 `BeamSearch + CUDA + flash_attn` 组合下会静默失败\n（forward pass 被跳过、瞬间返回 0 段）。本配置默认开启 flash_attn 是因为\n默认解码策略是 Greedy，与 flash_attn 兼容。如果手动调到 BeamSearch\n但发现段数总是 0，请把这里关掉。'),
  "model_filename": zod.string().describe('模型文件名'),
  "use_gpu": zod.boolean().describe('是否使用 GPU')
}).describe('whisper 引擎运行时配置（影响模型加载，启动期决定）'),
  "whisper_transcribe_config": zod.object({
  "anti_hallucination": zod.boolean().describe('启用抗幻觉\/重复参数组合\n（`temperature_inc` \/ `entropy_thold` \/ `logprob_thold` \/ `no_speech_thold` \/ ...）。\n\n\*\*默认 `false`\*\*。这些参数虽然多数与 whisper.cpp 默认值相同，但\*\*显式调用\nset_xxx\*\* 在某些 CUDA build 上会让 forward pass 异常瞬退、整段返回 0。\n本机确认能正常出字幕后再开启可获得更稳定的\"不识别 → 跳过\"行为。'),
  "auto_gain": zod.boolean().describe('是否在低音量片段做自动增益（peak<0.02 时拉到 0.8，封顶 20x）'),
  "beam_size": zod.number().describe('beam search 束宽：> 1 走 BeamSearch；<= 1 走 Greedy。\n\n默认 1（Greedy）。BeamSearch 理论上更准，但部分 whisper.cpp CUDA 编译版本\n会\"静默失败\"——forward pass 被跳过、瞬间返回 0 段。本机验证 OK 后再调高。'),
  "greedy_best_of": zod.number().describe('Greedy 模式下的候选数 best_of，仅当 `beam_size <= 1` 时生效。\n\n默认 1：与旧版 best_of 行为一致，确保 GPU 后端不会走异常 kernel 路径。\n验证当前 build 兼容后可调到 5（whisper.cpp 默认值），轻微降低重复幻觉。'),
  "initial_prompt": zod.string().nullish().describe('初始 prompt：可放专有名词、人名、风格示例（如 \"以下是普通话简体中文字幕。\"）。\n为 `None` 时不调用 `set_initial_prompt`。'),
  "language": zod.string().nullish().describe('语言代码：\n- `None`：完全用 whisper.cpp 编译默认（通常是 \"en\"），不调用 `set_xxx`。\n  最稳，与本机验证可工作的旧版兼容。\n- `Some(\"auto\")`：调用 `set_detect_language(true)` 自动检测。\*\*警告\*\*：\n  某些 CUDA build 下检测路径会让 forward pass 异常瞬退，遇到 0 段时回 `None`。\n- `Some(\"zh\"\/\"en\"\/...)`：显式锁定语言代码。'),
  "n_threads": zod.number().describe('CPU 解码线程数。0 表示 `whisper.cpp` 自动（min(4, hw_concurrency)）。')
}).describe('whisper 解码可调参数（影响每次 transcribe 行为）')
}).describe('应用设置：识别流水线默认参数 + 翻译默认参数 + Stash 连接。')


/**
 * @summary 更新全局配置并持久化；`api_key` 为空则保留原密钥。
 */
export const putAppConfigSettingsBodyVadConfigFrameMsMin = 0;

export const putAppConfigSettingsBodyVadConfigMaxSegmentMsMin = 0;

export const putAppConfigSettingsBodyVadConfigMinSpeechMsMin = 0;

export const putAppConfigSettingsBodyVadConfigModeMin = 0;

export const putAppConfigSettingsBodyVadConfigPaddingMsMin = 0;



export const PutAppConfigSettingsBody = zod.object({
  "stash_config": zod.object({
  "api_key": zod.string().describe('GraphQL \/ 媒体请求使用的 ApiKey；无鉴权时可留空'),
  "base_url": zod.string().describe('实例根地址，如 `http:\/\/127.0.0.1:9999`'),
  "path_mappings": zod.array(zod.object({
  "local_prefix": zod.string().describe('本服务运行环境可访问的本地路径前缀。'),
  "stash_prefix": zod.string().describe('Stash 返回的文件路径前缀。')
}).describe('Stash 文件路径到本服务本地路径的前缀映射。')).optional().describe('Stash 视角文件路径到本服务本地文件路径的前缀映射。')
}).optional().describe('旧版 `app_config.json` 无此字段时反序列化为 [`StashConnectConfig::default`]。'),
  "translate_config": zod.object({
  "api_key": zod.string().describe('调用模型的 API 密钥'),
  "base_url": zod.string().describe('调用模型的基础 URL'),
  "batch_size": zod.number().describe('单批字幕条数。`>1` 时启用批量上下文翻译，`=1` 走逐条翻译。 默认 8'),
  "concurrency": zod.number().describe('并发数（同时在飞的请求数） 默认 4'),
  "model": zod.string().describe('模型名，默认 `tencent\/Hunyuan-MT-7B`'),
  "remove_source_srt": zod.boolean().describe('是否在翻译完成后删除原文 SRT。默认 `false`，两份文件并存便于核对。'),
  "target_language": zod.string().describe('目标语言，例如 \"Chinese\"、\"English\"、\"Japanese\"')
}).describe('翻译选项'),
  "vad_config": zod.object({
  "frame_ms": zod.number().min(putAppConfigSettingsBodyVadConfigFrameMsMin).describe('帧长 10\/20\/30（默认 30）'),
  "max_segment_ms": zod.number().min(putAppConfigSettingsBodyVadConfigMaxSegmentMsMin).describe('单段最大长度（ms），超过会被硬切。`0` 表示不限制。\n默认 30000（30s）：whisper 内部以 30s 滑窗解码，限到 30s 速度与上下文都更稳。'),
  "min_speech_ms": zod.number().min(putAppConfigSettingsBodyVadConfigMinSpeechMsMin).describe('丢弃短于该值的语音段（ms）（默认 200）'),
  "mode": zod.number().min(putAppConfigSettingsBodyVadConfigModeMin).describe('模式 0..=3（越大越激进，默认 2）'),
  "padding_ms": zod.number().min(putAppConfigSettingsBodyVadConfigPaddingMsMin).describe('语音段两侧 padding（ms）（默认 300）')
}).describe('VAD 配置'),
  "whisper_engine_config": zod.object({
  "flash_attn": zod.boolean().describe('是否启用 flash attention。\n\n注意：whisper.cpp 在 `BeamSearch + CUDA + flash_attn` 组合下会静默失败\n（forward pass 被跳过、瞬间返回 0 段）。本配置默认开启 flash_attn 是因为\n默认解码策略是 Greedy，与 flash_attn 兼容。如果手动调到 BeamSearch\n但发现段数总是 0，请把这里关掉。'),
  "model_filename": zod.string().describe('模型文件名'),
  "use_gpu": zod.boolean().describe('是否使用 GPU')
}).describe('whisper 引擎运行时配置（影响模型加载，启动期决定）'),
  "whisper_transcribe_config": zod.object({
  "anti_hallucination": zod.boolean().describe('启用抗幻觉\/重复参数组合\n（`temperature_inc` \/ `entropy_thold` \/ `logprob_thold` \/ `no_speech_thold` \/ ...）。\n\n\*\*默认 `false`\*\*。这些参数虽然多数与 whisper.cpp 默认值相同，但\*\*显式调用\nset_xxx\*\* 在某些 CUDA build 上会让 forward pass 异常瞬退、整段返回 0。\n本机确认能正常出字幕后再开启可获得更稳定的\"不识别 → 跳过\"行为。'),
  "auto_gain": zod.boolean().describe('是否在低音量片段做自动增益（peak<0.02 时拉到 0.8，封顶 20x）'),
  "beam_size": zod.number().describe('beam search 束宽：> 1 走 BeamSearch；<= 1 走 Greedy。\n\n默认 1（Greedy）。BeamSearch 理论上更准，但部分 whisper.cpp CUDA 编译版本\n会\"静默失败\"——forward pass 被跳过、瞬间返回 0 段。本机验证 OK 后再调高。'),
  "greedy_best_of": zod.number().describe('Greedy 模式下的候选数 best_of，仅当 `beam_size <= 1` 时生效。\n\n默认 1：与旧版 best_of 行为一致，确保 GPU 后端不会走异常 kernel 路径。\n验证当前 build 兼容后可调到 5（whisper.cpp 默认值），轻微降低重复幻觉。'),
  "initial_prompt": zod.string().nullish().describe('初始 prompt：可放专有名词、人名、风格示例（如 \"以下是普通话简体中文字幕。\"）。\n为 `None` 时不调用 `set_initial_prompt`。'),
  "language": zod.string().nullish().describe('语言代码：\n- `None`：完全用 whisper.cpp 编译默认（通常是 \"en\"），不调用 `set_xxx`。\n  最稳，与本机验证可工作的旧版兼容。\n- `Some(\"auto\")`：调用 `set_detect_language(true)` 自动检测。\*\*警告\*\*：\n  某些 CUDA build 下检测路径会让 forward pass 异常瞬退，遇到 0 段时回 `None`。\n- `Some(\"zh\"\/\"en\"\/...)`：显式锁定语言代码。'),
  "n_threads": zod.number().describe('CPU 解码线程数。0 表示 `whisper.cpp` 自动（min(4, hw_concurrency)）。')
}).describe('whisper 解码可调参数（影响每次 transcribe 行为）')
}).describe('应用设置：识别流水线默认参数 + 翻译默认参数 + Stash 连接。')

export const putAppConfigSettingsResponseVadConfigFrameMsMin = 0;

export const putAppConfigSettingsResponseVadConfigMaxSegmentMsMin = 0;

export const putAppConfigSettingsResponseVadConfigMinSpeechMsMin = 0;

export const putAppConfigSettingsResponseVadConfigModeMin = 0;

export const putAppConfigSettingsResponseVadConfigPaddingMsMin = 0;



export const PutAppConfigSettingsResponse = zod.object({
  "stash_config": zod.object({
  "api_key": zod.string().describe('GraphQL \/ 媒体请求使用的 ApiKey；无鉴权时可留空'),
  "base_url": zod.string().describe('实例根地址，如 `http:\/\/127.0.0.1:9999`'),
  "path_mappings": zod.array(zod.object({
  "local_prefix": zod.string().describe('本服务运行环境可访问的本地路径前缀。'),
  "stash_prefix": zod.string().describe('Stash 返回的文件路径前缀。')
}).describe('Stash 文件路径到本服务本地路径的前缀映射。')).optional().describe('Stash 视角文件路径到本服务本地文件路径的前缀映射。')
}).optional().describe('旧版 `app_config.json` 无此字段时反序列化为 [`StashConnectConfig::default`]。'),
  "translate_config": zod.object({
  "api_key": zod.string().describe('调用模型的 API 密钥'),
  "base_url": zod.string().describe('调用模型的基础 URL'),
  "batch_size": zod.number().describe('单批字幕条数。`>1` 时启用批量上下文翻译，`=1` 走逐条翻译。 默认 8'),
  "concurrency": zod.number().describe('并发数（同时在飞的请求数） 默认 4'),
  "model": zod.string().describe('模型名，默认 `tencent\/Hunyuan-MT-7B`'),
  "remove_source_srt": zod.boolean().describe('是否在翻译完成后删除原文 SRT。默认 `false`，两份文件并存便于核对。'),
  "target_language": zod.string().describe('目标语言，例如 \"Chinese\"、\"English\"、\"Japanese\"')
}).describe('翻译选项'),
  "vad_config": zod.object({
  "frame_ms": zod.number().min(putAppConfigSettingsResponseVadConfigFrameMsMin).describe('帧长 10\/20\/30（默认 30）'),
  "max_segment_ms": zod.number().min(putAppConfigSettingsResponseVadConfigMaxSegmentMsMin).describe('单段最大长度（ms），超过会被硬切。`0` 表示不限制。\n默认 30000（30s）：whisper 内部以 30s 滑窗解码，限到 30s 速度与上下文都更稳。'),
  "min_speech_ms": zod.number().min(putAppConfigSettingsResponseVadConfigMinSpeechMsMin).describe('丢弃短于该值的语音段（ms）（默认 200）'),
  "mode": zod.number().min(putAppConfigSettingsResponseVadConfigModeMin).describe('模式 0..=3（越大越激进，默认 2）'),
  "padding_ms": zod.number().min(putAppConfigSettingsResponseVadConfigPaddingMsMin).describe('语音段两侧 padding（ms）（默认 300）')
}).describe('VAD 配置'),
  "whisper_engine_config": zod.object({
  "flash_attn": zod.boolean().describe('是否启用 flash attention。\n\n注意：whisper.cpp 在 `BeamSearch + CUDA + flash_attn` 组合下会静默失败\n（forward pass 被跳过、瞬间返回 0 段）。本配置默认开启 flash_attn 是因为\n默认解码策略是 Greedy，与 flash_attn 兼容。如果手动调到 BeamSearch\n但发现段数总是 0，请把这里关掉。'),
  "model_filename": zod.string().describe('模型文件名'),
  "use_gpu": zod.boolean().describe('是否使用 GPU')
}).describe('whisper 引擎运行时配置（影响模型加载，启动期决定）'),
  "whisper_transcribe_config": zod.object({
  "anti_hallucination": zod.boolean().describe('启用抗幻觉\/重复参数组合\n（`temperature_inc` \/ `entropy_thold` \/ `logprob_thold` \/ `no_speech_thold` \/ ...）。\n\n\*\*默认 `false`\*\*。这些参数虽然多数与 whisper.cpp 默认值相同，但\*\*显式调用\nset_xxx\*\* 在某些 CUDA build 上会让 forward pass 异常瞬退、整段返回 0。\n本机确认能正常出字幕后再开启可获得更稳定的\"不识别 → 跳过\"行为。'),
  "auto_gain": zod.boolean().describe('是否在低音量片段做自动增益（peak<0.02 时拉到 0.8，封顶 20x）'),
  "beam_size": zod.number().describe('beam search 束宽：> 1 走 BeamSearch；<= 1 走 Greedy。\n\n默认 1（Greedy）。BeamSearch 理论上更准，但部分 whisper.cpp CUDA 编译版本\n会\"静默失败\"——forward pass 被跳过、瞬间返回 0 段。本机验证 OK 后再调高。'),
  "greedy_best_of": zod.number().describe('Greedy 模式下的候选数 best_of，仅当 `beam_size <= 1` 时生效。\n\n默认 1：与旧版 best_of 行为一致，确保 GPU 后端不会走异常 kernel 路径。\n验证当前 build 兼容后可调到 5（whisper.cpp 默认值），轻微降低重复幻觉。'),
  "initial_prompt": zod.string().nullish().describe('初始 prompt：可放专有名词、人名、风格示例（如 \"以下是普通话简体中文字幕。\"）。\n为 `None` 时不调用 `set_initial_prompt`。'),
  "language": zod.string().nullish().describe('语言代码：\n- `None`：完全用 whisper.cpp 编译默认（通常是 \"en\"），不调用 `set_xxx`。\n  最稳，与本机验证可工作的旧版兼容。\n- `Some(\"auto\")`：调用 `set_detect_language(true)` 自动检测。\*\*警告\*\*：\n  某些 CUDA build 下检测路径会让 forward pass 异常瞬退，遇到 0 段时回 `None`。\n- `Some(\"zh\"\/\"en\"\/...)`：显式锁定语言代码。'),
  "n_threads": zod.number().describe('CPU 解码线程数。0 表示 `whisper.cpp` 自动（min(4, hw_concurrency)）。')
}).describe('whisper 解码可调参数（影响每次 transcribe 行为）')
}).describe('应用设置：识别流水线默认参数 + 翻译默认参数 + Stash 连接。')


export const DownloadFfmpegSetupBody = zod.looseObject({

})

export const DownloadFfmpegSetupResponse = zod.object({
  "job_id": zod.string()
})


export const FfmpegStatusSetupResponse = zod.object({
  "local_ready": zod.boolean()
}).describe('FFmpeg 工具目录是否已安装可执行文件')


export const DownloadWhisperSetupBody = zod.object({
  "model_id": zod.string()
})

export const DownloadWhisperSetupResponse = zod.object({
  "job_id": zod.string()
})


export const ListWhisperModelsSetupResponse = zod.object({
  "items": zod.array(zod.object({
  "description": zod.string(),
  "filename": zod.string(),
  "id": zod.string(),
  "label": zod.string(),
  "local_ready": zod.boolean().describe('模型目录下是否已有同名文件'),
  "size_hint": zod.string().describe('人类可读大小，如 \"3.1 GiB\"')
}).describe('Whisper 可下载项（静态目录）'))
})


export const ListScenesStashBody = zod.object({
  "filter": zod.object({
  "direction": zod.string().nullish().describe('`ASC` 或 `DESC`'),
  "page": zod.number().optional(),
  "page_size": zod.number().optional(),
  "q": zod.string().nullish(),
  "sort": zod.string().nullish()
}).describe('Stash 场景列表查询（分页字段与 ProTable 对齐，服务端映射为 Stash `FindFilterType`）'),
  "scene_filter": zod.union([zod.null(),zod.object({
  "AND": zod.union([zod.null(),zod.unknown()]).optional(),
  "NOT": zod.union([zod.null(),zod.unknown()]).optional(),
  "OR": zod.union([zod.null(),zod.unknown()]).optional(),
  "audio_codec": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "bitrate": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "captions": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "checksum": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "code": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "created_at": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string(),
  "value2": zod.string().nullish()
}).describe('Stash `DateCriterionInput` \/ `TimestampCriterionInput`')]).optional(),
  "custom_fields": zod.array(zod.object({
  "field": zod.string(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.array(zod.unknown())
}).describe('Stash `CustomFieldCriterionInput`（`value` 为 GraphQL `Any`，透传 JSON）')).nullish(),
  "date": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string(),
  "value2": zod.string().nullish()
}).describe('Stash `DateCriterionInput` \/ `TimestampCriterionInput`')]).optional(),
  "details": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "director": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "duplicated": zod.union([zod.null(),zod.object({
  "distance": zod.number().nullish(),
  "phash": zod.boolean().nullish(),
  "stash_id": zod.boolean().nullish(),
  "title": zod.boolean().nullish(),
  "url": zod.boolean().nullish()
}).describe('Stash `DuplicationCriterionInput`')]).optional(),
  "duration": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "file_count": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "files_filter": zod.unknown().optional(),
  "framerate": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "galleries": zod.union([zod.null(),zod.object({
  "excludes": zod.array(zod.string()).nullish(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.array(zod.string()).nullish()
}).describe('Stash `MultiCriterionInput`')]).optional(),
  "galleries_filter": zod.unknown().optional().describe('关联实体过滤器（结构体庞大，按需透传 Stash 原生 JSON）'),
  "groups": zod.union([zod.null(),zod.object({
  "depth": zod.number().nullish(),
  "excludes": zod.array(zod.string()).nullish(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.array(zod.string()).nullish()
}).describe('Stash `HierarchicalMultiCriterionInput`')]).optional(),
  "groups_filter": zod.unknown().optional(),
  "has_markers": zod.string().nullish(),
  "id": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "interactive": zod.boolean().nullish(),
  "interactive_speed": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "is_missing": zod.string().nullish(),
  "last_played_at": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string(),
  "value2": zod.string().nullish()
}).describe('Stash `DateCriterionInput` \/ `TimestampCriterionInput`')]).optional(),
  "markers_filter": zod.unknown().optional(),
  "movies": zod.union([zod.null(),zod.object({
  "excludes": zod.array(zod.string()).nullish(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.array(zod.string()).nullish()
}).describe('Stash `MultiCriterionInput`')]).optional(),
  "movies_filter": zod.unknown().optional(),
  "o_counter": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "organized": zod.boolean().nullish(),
  "orientation": zod.union([zod.null(),zod.object({
  "value": zod.array(zod.enum(['LANDSCAPE', 'PORTRAIT', 'SQUARE']).describe('Stash `OrientationEnum`'))
}).describe('Stash `OrientationCriterionInput`')]).optional(),
  "oshash": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "path": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "performer_age": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "performer_count": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "performer_favorite": zod.boolean().nullish(),
  "performer_tags": zod.union([zod.null(),zod.object({
  "depth": zod.number().nullish(),
  "excludes": zod.array(zod.string()).nullish(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.array(zod.string()).nullish()
}).describe('Stash `HierarchicalMultiCriterionInput`')]).optional(),
  "performers": zod.union([zod.null(),zod.object({
  "excludes": zod.array(zod.string()).nullish(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.array(zod.string()).nullish()
}).describe('Stash `MultiCriterionInput`')]).optional(),
  "performers_filter": zod.unknown().optional(),
  "phash": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "phash_distance": zod.union([zod.null(),zod.object({
  "distance": zod.number().nullish(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `PhashDistanceCriterionInput`')]).optional(),
  "play_count": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "play_duration": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "rating100": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "resolution": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.enum(['VERY_LOW', 'LOW', 'R360P', 'STANDARD', 'WEB_HD', 'STANDARD_HD', 'FULL_HD', 'QUAD_HD', 'FOUR_K', 'FIVE_K', 'SIX_K', 'SEVEN_K', 'EIGHT_K', 'HUGE']).describe('Stash `ResolutionEnum`')
}).describe('Stash `ResolutionCriterionInput`')]).optional(),
  "resume_time": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "stash_id_count": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "stash_id_endpoint": zod.union([zod.null(),zod.object({
  "endpoint": zod.string().nullish(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "stash_id": zod.string().nullish()
}).describe('Stash `StashIDCriterionInput`')]).optional(),
  "stash_ids_endpoint": zod.union([zod.null(),zod.object({
  "endpoint": zod.string().nullish(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "stash_ids": zod.array(zod.string()).nullish()
}).describe('Stash `StashIDsCriterionInput`')]).optional(),
  "studios": zod.union([zod.null(),zod.object({
  "depth": zod.number().nullish(),
  "excludes": zod.array(zod.string()).nullish(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.array(zod.string()).nullish()
}).describe('Stash `HierarchicalMultiCriterionInput`')]).optional(),
  "studios_filter": zod.unknown().optional(),
  "tag_count": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.number(),
  "value2": zod.number().nullish()
}).describe('Stash `IntCriterionInput`')]).optional(),
  "tags": zod.union([zod.null(),zod.object({
  "depth": zod.number().nullish(),
  "excludes": zod.array(zod.string()).nullish(),
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.array(zod.string()).nullish()
}).describe('Stash `HierarchicalMultiCriterionInput`')]).optional(),
  "tags_filter": zod.unknown().optional(),
  "title": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "updated_at": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string(),
  "value2": zod.string().nullish()
}).describe('Stash `DateCriterionInput` \/ `TimestampCriterionInput`')]).optional(),
  "url": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional(),
  "video_codec": zod.union([zod.null(),zod.object({
  "modifier": zod.enum(['=', 'Equals', '!=', 'NotEquals', '>', 'GreaterThan', '<', 'LessThan', 'IS NULL', 'IS NOT NULL', 'INCLUDES ALL', 'Includes', 'Excludes', 'MATCHES REGEX', 'NOT MATCHES REGEX', '>= AND <=', '< OR >']).describe('Stash `CriterionModifier`（与 GraphQL 枚举值一致）'),
  "value": zod.string()
}).describe('Stash `StringCriterionInput`')]).optional()
}).describe('对应 GraphQL `SceneFilterType`')]).optional(),
  "scene_ids": zod.array(zod.number()).nullish().describe('对应 GraphQL `scene_ids`')
})

export const ListScenesStashResponse = zod.object({
  "data": zod.array(zod.object({
  "date": zod.string().nullish(),
  "files": zod.array(zod.object({
  "basename": zod.string(),
  "local_path": zod.string().nullish().describe('根据 `stash_config.path_mappings` 映射出的本服务本地路径。'),
  "path": zod.string()
})),
  "id": zod.string(),
  "paths": zod.object({
  "preview": zod.string(),
  "screenshot": zod.string()
}),
  "title": zod.string()
})),
  "total": zod.number()
})


export const DownloadSubtitleWebBody = zod.object({
  "subtitle_id": zod.string(),
  "video_path": zod.string()
})

export const DownloadSubtitleWebResponse = zod.object({
  "record_id": zod.number(),
  "subtitle_path": zod.string()
})


export const SearchSubtitleWebBody = zod.object({
  "video_path": zod.string()
})

export const SearchSubtitleWebResponse = zod.object({
  "cid": zod.string().describe('视频的 cid'),
  "items": zod.array(zod.object({
  "ext": zod.string(),
  "id": zod.string(),
  "is_hash_match": zod.boolean(),
  "langs": zod.string(),
  "name": zod.string()
}).describe('搜索字幕结果 - 列表单项')).describe('字幕列表'),
  "video_path": zod.string().describe('视频的绝对路径')
}).describe('搜索字幕结果')
